/* AUTO-GENERATED by scripts/fetch-pricing.ts. Do not edit by hand. */
/* eslint-disable */
import type { GeneratedPricing } from './pricing-types';

export const GENERATED_PRICING: GeneratedPricing | null = null;
