/* AUTO-GENERATED by scripts/fetch-pricing.ts. Do not edit by hand. */
/* eslint-disable */
import type { GeneratedPricing } from './pricing-types';

export const GENERATED_PRICING: GeneratedPricing = {
  "fetchedAt": "2026-08-22T12:04:29.174Z",
  "currency": "USD",
  "plans": {
    "pro": {
      "price": {
        "monthly": 25,
        "annual": 199
      },
      "freemiusPlanIds": {
        "monthly": "55196",
        "annual": "55197"
      }
    }
  }
};
