/**
 * The words a mask request uses, and what the detector can and cannot name (AM2.1).
 *
 * MD-6 decided there is no text-grounding model in v1: candidates come from Subject
 * Intelligence (faces, people, and objects) and anything else is `needs_click`. This table is
 * that decision written down. The OUT_OF_VOCABULARY list exists so "the sky" is recognised as
 * something the editor has to click, rather than falling through to "no such object" — and so
 * the `needs_click` rate the eval reports separately (plan 06) is a designed outcome, not a miss.
 */

/** A face: YuNet boxes. */
export const FACE_WORDS: ReadonlySet<string> = new Set(['face', 'faces', 'head', 'heads']);

/** A person: the detector's `person` label. Pronouns included — "put the title behind her". */
export const PERSON_WORDS: ReadonlySet<string> = new Set([
  'person',
  'people',
  'persons',
  'man',
  'men',
  'woman',
  'women',
  'guy',
  'guys',
  'girl',
  'girls',
  'boy',
  'boys',
  'kid',
  'kids',
  'child',
  'children',
  'baby',
  'subject',
  'subjects',
  'someone',
  'everyone',
  'everybody',
  'anyone',
  'her',
  'him',
  'them',
  'she',
  'he',
  'they',
  'crowd',
  'audience',
  'passerby',
  'passersby',
  'bystander',
  'bystanders',
  'player',
  'players',
  // People named by what they are doing or where they are — still the detector's `person`.
  'pedestrian',
  'pedestrians',
  'walker',
  'walkers',
  'cyclist',
  'cyclists',
  'rider',
  'riders',
  'runner',
  'runners',
  'dancer',
  'dancers',
  'skater',
  'skaters',
  'surfer',
  'surfers',
  'athlete',
  'athletes',
  'worker',
  'workers',
  'customer',
  'customers',
  'shopper',
  'shoppers',
  'tourist',
  'tourists',
  'spectator',
  'spectators',
  'student',
  'students',
  'owner',
  'owners',
  'singer',
  'singers',
  'musician',
  'musicians',
  'actor',
  'actors',
  'actress',
  'lady',
  'ladies',
  'gentleman',
  'teenager',
  'teenagers',
  'toddler',
  'adult',
  'adults',
]);

/** Roles: a person, but WHICH one is a question of identity, not of detection. */
export const ROLE_WORDS: ReadonlySet<string> = new Set([
  'host',
  'hosts',
  'presenter',
  'presenters',
  'speaker',
  'speakers',
  'interviewer',
  'interviewee',
  'guest',
  'guests',
  'narrator',
  'anchor',
  'reporter',
  'teacher',
  'instructor',
]);

/** Things the object detector was trained on (COCO), with the words editors use for them. */
export const OBJECT_WORDS: ReadonlySet<string> = new Set([
  'object',
  'objects',
  'thing',
  'item',
  'product',
  'products',
  'car',
  'cars',
  'vehicle',
  'vehicles',
  'truck',
  'trucks',
  'bus',
  'buses',
  'van',
  'taxi',
  'bicycle',
  'bicycles',
  'bike',
  'bikes',
  'motorcycle',
  'motorcycles',
  'motorbike',
  'scooter',
  'train',
  'trains',
  'boat',
  'boats',
  'ship',
  'airplane',
  'plane',
  'planes',
  'aeroplane',
  'dog',
  'dogs',
  'puppy',
  'cat',
  'cats',
  'kitten',
  'bird',
  'birds',
  'horse',
  'horses',
  'sheep',
  'cow',
  'cows',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'pet',
  'pets',
  'animal',
  'animals',
  'phone',
  'phones',
  'cellphone',
  'smartphone',
  'laptop',
  'laptops',
  'computer',
  'keyboard',
  'mouse',
  'remote',
  'tv',
  'television',
  'monitor',
  'screen',
  'screens',
  'bottle',
  'bottles',
  'cup',
  'cups',
  'mug',
  'glass',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'chair',
  'chairs',
  'couch',
  'sofa',
  'bed',
  'table',
  'desk',
  'bench',
  'toilet',
  'sink',
  'refrigerator',
  'fridge',
  'oven',
  'microwave',
  'toaster',
  'vase',
  'clock',
  'book',
  'books',
  'backpack',
  'bag',
  'bags',
  'handbag',
  'suitcase',
  'umbrella',
  'tie',
  'ball',
  'football',
  'frisbee',
  'kite',
  'skateboard',
  'surfboard',
  'snowboard',
  'skis',
  'racket',
  'banana',
  'apple',
  'orange',
  'sandwich',
  'pizza',
  'cake',
  'donut',
  'carrot',
  'broccoli',
  'plant',
  'plants',
  'scissors',
  'toothbrush',
  'hydrant',
  'teddy',
]);

/** Named, and not something the detector boxes: the editor clicks it once (`needs_click`). */
export const OUT_OF_VOCABULARY_WORDS: ReadonlySet<string> = new Set([
  'sky',
  'skies',
  'cloud',
  'clouds',
  'sun',
  'moon',
  'sea',
  'ocean',
  'water',
  'river',
  'lake',
  'grass',
  'ground',
  'floor',
  'road',
  'street',
  'pavement',
  'wall',
  'walls',
  'ceiling',
  'window',
  'windows',
  'door',
  'building',
  'buildings',
  'tree',
  'trees',
  'mountain',
  'mountains',
  'sign',
  'signs',
  'signage',
  'billboard',
  'poster',
  'logo',
  'logos',
  'brand',
  'watermark',
  'plate',
  'plates',
  'licence',
  'license',
  'numberplate',
  'text',
  'writing',
  'label',
  'labels',
  'tattoo',
  'tattoos',
  'hair',
  'hand',
  'hands',
  'eyes',
  'shirt',
  'jacket',
  'dress',
  'hat',
  'reflection',
  'shadow',
  'light',
  'lamp',
  'fire',
  'smoke',
  'whiteboard',
  'painting',
]);

/** Words that ask for every match rather than one. */
export const ALL_WORDS: ReadonlySet<string> = new Set([
  'all',
  'every',
  'each',
  'everyone',
  'everybody',
  'both',
  'any',
  'anyone',
]);

/** Words that exclude someone — which only identity can answer. */
export const EXCEPTION_PHRASES: readonly RegExp[] = [
  /\bexcept\b/u,
  /\bother than\b/u,
  /\bbut not\b/u,
  /\bapart from\b/u,
  /\bnot the\b/u,
  /\bexcluding\b/u,
];

/** Positional and size selectors the geometry itself can answer. */
export const SELECTOR_WORDS: Readonly<
  Record<string, 'left' | 'right' | 'center' | 'largest' | 'smallest' | 'top' | 'bottom'>
> = {
  left: 'left',
  leftmost: 'left',
  right: 'right',
  rightmost: 'right',
  center: 'center',
  centre: 'center',
  middle: 'center',
  central: 'center',
  biggest: 'largest',
  largest: 'largest',
  closest: 'largest',
  nearest: 'largest',
  main: 'largest',
  foreground: 'largest',
  smallest: 'smallest',
  furthest: 'smallest',
  farthest: 'smallest',
  top: 'top',
  upper: 'top',
  bottom: 'bottom',
  lower: 'bottom',
};

/** Words that carry no information about which thing is meant. */
export const STOP_WORDS: ReadonlySet<string> = new Set([
  'the',
  'a',
  'an',
  'of',
  'on',
  'in',
  'at',
  'to',
  'and',
  'or',
  'with',
  'from',
  'side',
  'one',
  'this',
  'that',
  'those',
  'these',
  'is',
  'are',
  'who',
  'which',
  'whos',
  'its',
  'their',
  'his',
  'hers',
  'my',
  'our',
  'your',
  's',
  'please',
  'just',
  'only',
  'mask',
  'blur',
  'hide',
  'track',
  'isolate',
  'cut',
  'out',
  'remove',
  'grade',
  'behind',
  'front',
  'frame',
  'shot',
  'clip',
  'picture',
  'image',
  'video',
  'there',
  'here',
  'up',
  'down',
  'most',
  'part',
]);
