/**
 * The sticker catalogue (plan/elements EL6a.2, 03 §2): Microsoft Fluent Emoji 3D (MIT) at a pinned
 * commit, generated by `scripts/elements/build_library.py` into `sticker-catalog.generated.ts`.
 *
 * One typed loader and one search, shared by the Stickers tab, the desktop main process (which
 * materialises a sticker's file into the project) and the agent (`search_elements`,
 * `add_sticker`), so a word typed and a word asked for find the same sticker.
 *
 * The data is ~0.5 MB, so it is loaded on first use ({@link loadStickerCatalog}): the renderer
 * gets it as a separate chunk and the editor's start-up does not carry it.
 */

/** Where a sticker's file comes from in this build. */
export type StickerAvailability =
  /** Curated: its files are committed and ship in every build. */
  | 'bundled'
  /** The rest of the library: shipped by the desktop installer (EL6b), not in this build yet. */
  | 'packaged';

export interface StickerItem {
  /** Snake-case CLDR name (`thumbs_up`): the element id the agent and the IPC name. */
  readonly id: string;
  readonly name: string;
  /** The emoji itself; searching for it finds the sticker. */
  readonly glyph: string;
  readonly unicode: string | null;
  /** The upstream group (`Smileys & Emotion`, `Food & Drink`, …). */
  readonly group: string;
  /** FramePilot collections it belongs to (`reactions`, `celebrate`, …), in collection order. */
  readonly collections: readonly string[];
  /** Its place in the curated collections, flattened; absent outside them. */
  readonly rank?: number;
  readonly keywords: readonly string[];
  readonly availability: StickerAvailability;
  /** The upstream file it was built from, relative to the catalogue's `sourceBase`. */
  readonly source: string;
  /** Bundled items: the padded full file, relative to the stickers folder (`full/<id>.webp`). */
  readonly file?: string;
  /** Bundled items: the 144 px tile (`thumbs/<id>.webp`). */
  readonly thumb?: string;
  /** Bundled items: SHA-256 of the full file, checked before every copy into a project. */
  readonly sha256?: string;
  readonly bytes?: number;
  /** The full file's pixel size (the art plus a 12% transparent margin on every side). */
  readonly width?: number;
  readonly height?: number;
  /** The art's own size inside that margin: how large it can be drawn and stay sharp. */
  readonly sharpSize?: number;
}

export interface StickerCollection {
  readonly id: string;
  readonly name: string;
}

export interface StickerCatalogData {
  readonly spec: string;
  /** The library key in element ids (`element_<library>_<id>`). */
  readonly library: string;
  /** The provider recorded in an asset's `source.provider`. */
  readonly provider: string;
  readonly commit: string;
  readonly license: string;
  readonly licenseUrl: string;
  readonly attribution: string;
  readonly creator: string;
  readonly attributionRequired: boolean;
  readonly sourceBase: string;
  readonly collections: readonly StickerCollection[];
  readonly items: readonly StickerItem[];
}

/** The catalogue with lookups built once. */
export interface StickerCatalog extends StickerCatalogData {
  /** The item called `id`, or `undefined`. */
  readonly byId: ReadonlyMap<string, StickerItem>;
}

/** An element id the IPC and the agent may name: a catalogue id, nothing path-shaped. */
export const STICKER_ID_PATTERN = /^[a-z0-9_]{1,96}$/;

/**
 * Why a sticker could not be put into the project: the desktop library's closed union
 * (`ElementErrorCodeWire` over IPC), exported so every sentence for it can be walked.
 */
export const ELEMENT_ERROR_CODES = [
  'unknown_element',
  'library_missing',
  'integrity_failed',
  'disk_full',
  'io_failed',
] as const;
export type ElementErrorCode = (typeof ELEMENT_ERROR_CODES)[number];

/** The sticker catalogue from its data (tests pass their own). */
export function stickerCatalog(data: StickerCatalogData): StickerCatalog {
  return { ...data, byId: new Map(data.items.map((item) => [item.id, item])) };
}

let loading: Promise<StickerCatalog> | undefined;

/** The generated catalogue, loaded once on first use. */
export function loadStickerCatalog(): Promise<StickerCatalog> {
  loading ??= import('./sticker-catalog.generated.js').then((module) =>
    stickerCatalog(module.STICKER_CATALOG_DATA),
  );
  return loading;
}

/** A sticker's upstream source URL (provenance for the asset it becomes). */
export function stickerSourceUrl(catalog: StickerCatalogData, item: StickerItem): string {
  return `${catalog.sourceBase}${item.source.split('/').map(encodeURIComponent).join('/')}`;
}

export interface StickerSearchOptions {
  /** Keep to one FramePilot collection (`reactions`, …). */
  readonly collection?: string;
  /** Keep to one upstream group (`Food & Drink`, …). */
  readonly group?: string;
  /** The most hits to return; `total` still counts them all. */
  readonly limit?: number;
  /** Include `packaged` stickers (a build that has the installer's set). Default: bundled only. */
  readonly includePackaged?: boolean;
}

export interface StickerSearchResult {
  readonly items: readonly StickerItem[];
  readonly total: number;
}

const EMOJI_SELECTOR = /️/g;
const words = (text: string): string[] =>
  text
    .toLowerCase()
    .split(/[^\p{L}\p{N}+]+/u)
    .filter((word) => word !== '');

/**
 * How well `item` matches `query` (lower is better), or `null` (plan/elements 03 §2.4): the glyph
 * itself, then the exact name, a name that starts with the query, a keyword that does, then the
 * query anywhere in the name or a keyword. Every word of a multi-word query must match.
 */
function score(item: StickerItem, query: string): number | null {
  const glyph = query.replace(EMOJI_SELECTOR, '');
  if (glyph !== '' && item.glyph.replace(EMOJI_SELECTOR, '') === glyph) return 0;
  const name = item.name.toLowerCase();
  const q = query.toLowerCase().trim();
  if (name === q) return 1;
  if (name.startsWith(q)) return 2;
  const keywords = item.keywords.map((keyword) => keyword.toLowerCase());
  if (keywords.some((keyword) => keyword === q || keyword.startsWith(q))) return 3;
  const terms = words(q);
  if (terms.length === 0) return null;
  const haystack = [...words(name), ...keywords.flatMap(words)];
  return terms.every((term) =>
    haystack.some((word) => word.startsWith(term) || word.includes(term)),
  )
    ? 4
    : null;
}

/** Curated stickers first, in their collections' order, then the rest in catalogue order. */
function curatedOrder(a: StickerItem, b: StickerItem, ai: number, bi: number): number {
  const ar = a.rank ?? Number.POSITIVE_INFINITY;
  const br = b.rank ?? Number.POSITIVE_INFINITY;
  return ar !== br ? ar - br : ai - bi;
}

/**
 * The stickers `query` finds, best first. An empty query lists the scope (a collection, a group,
 * or everything) in curated order.
 */
export function searchStickers(
  catalog: StickerCatalogData,
  query: string,
  options: StickerSearchOptions = {},
): StickerSearchResult {
  const pool = catalog.items
    .map((item, index) => ({ item, index }))
    .filter(
      ({ item }) =>
        (options.includePackaged === true || item.availability === 'bundled') &&
        (options.collection === undefined || item.collections.includes(options.collection)) &&
        (options.group === undefined || item.group === options.group),
    );
  const q = query.trim();
  const ranked =
    q === ''
      ? pool.map((row) => ({ ...row, rank: 0 }))
      : pool
          .map((row) => ({ ...row, rank: score(row.item, q) }))
          .filter(
            (row): row is { item: StickerItem; index: number; rank: number } => row.rank !== null,
          );
  ranked.sort((a, b) => a.rank - b.rank || curatedOrder(a.item, b.item, a.index, b.index));
  const limit = options.limit ?? Number.POSITIVE_INFINITY;
  return { items: ranked.slice(0, limit).map((row) => row.item), total: ranked.length };
}
