/**
 * MK7.1: the monitor reads a transform track to the same float64 bytes the export does.
 *
 * A tracked mask's transform moves the path's CONTROL POINTS, and every later step of the
 * rasteriser is already pinned byte-exact against Python (`mask-raster.test.ts`), so a single ulp
 * here would be the one place a tracked mask could preview differently from the export. The
 * vectors are generated by `pnpm mask-track:vectors`.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  parseTrackArtifact,
  trackConfidenceAt,
  trackFrameIndexAt,
  trackMatrixAt,
  trackPointDelta,
  trackWarpPoint,
} from '@framepilot/editor-core';
import { MaskLayerSchema } from '@framepilot/timeline-schema';
import { trackedMaskPathAt, type ShapeMask } from './mask-stack.js';

interface VectorCase {
  readonly id: string;
  readonly track: string;
  readonly sourceSeconds: number;
  readonly frameIndex: number;
  readonly confidence: number;
  readonly expected: { readonly sha256: string; readonly count: number };
}

interface VectorDocument {
  readonly probePoints: readonly (readonly number[])[];
  readonly tracks: Readonly<Record<string, unknown>>;
  readonly cases: readonly VectorCase[];
}

const FIXTURE = path.resolve(__dirname, '../../../../../tests/fixtures/mask-track/transforms.json');

const document = JSON.parse(readFileSync(FIXTURE, 'utf-8')) as VectorDocument;

function digest(values: readonly number[]): string {
  const bytes = new Float64Array(values);
  return createHash('sha256').update(Buffer.from(bytes.buffer)).digest('hex');
}

describe('transform-track parity with the engine', () => {
  it('covers every method', () => {
    expect(Object.keys(document.tracks).sort()).toEqual([
      'perspective',
      'position',
      'shape',
      'similarity',
    ]);
  });

  it.each(document.cases.map((testCase) => [testCase.id, testCase] as const))(
    '%s',
    (_id, testCase) => {
      const artifact = parseTrackArtifact(document.tracks[testCase.track]);
      const index = trackFrameIndexAt(artifact, testCase.sourceSeconds);
      expect(index).toBe(testCase.frameIndex);
      expect(trackConfidenceAt(artifact, testCase.sourceSeconds)).toBe(testCase.confidence);
      const matrix = trackMatrixAt(artifact, index);
      const warped: number[] = [];
      for (const point of document.probePoints) {
        const [x, y] = trackWarpPoint(matrix, point[0]!, point[1]!);
        warped.push(x, y);
      }
      if (artifact.points !== undefined) {
        for (let vertex = 0; vertex <= artifact.points.count; vertex += 1) {
          const [dx, dy] = trackPointDelta(artifact, index, vertex);
          warped.push(dx, dy);
        }
      }
      expect(warped).toHaveLength(testCase.expected.count);
      expect(digest(warped)).toBe(testCase.expected.sha256);
    },
  );
});

interface CorrectedCase {
  readonly id: string;
  readonly mask: string;
  readonly track: string;
  readonly sourceSeconds: number;
  readonly expected: { readonly sha256: string; readonly count: number };
}

const corrected = JSON.parse(
  readFileSync(
    path.resolve(__dirname, '../../../../../tests/fixtures/mask-track/corrected.json'),
    'utf-8',
  ),
) as {
  readonly masks: Readonly<Record<string, unknown>>;
  readonly tracks: Readonly<Record<string, unknown>>;
  readonly cases: readonly CorrectedCase[];
};

/**
 * MK7.7: a mask corrected on one frame of its track — the correction keyed relative to the
 * tracked motion, held across the corrected stretch — is drawn `T(t) · G(t)` by the monitor to
 * the same bits as by the export, on, inside, before and after the stretch.
 */
describe('a corrected tracked mask draws the same as the export', () => {
  it('covers a path under perspective, a rectangle under a similarity and a shape track', () => {
    expect(Object.keys(corrected.masks).sort()).toEqual([
      'path-perspective',
      'path-shape',
      'rectangle-similarity',
    ]);
  });

  it.each(corrected.cases.map((testCase) => [testCase.id, testCase] as const))(
    '%s',
    (_id, testCase) => {
      const mask = MaskLayerSchema.parse(corrected.masks[testCase.mask]) as ShapeMask;
      const track = parseTrackArtifact(corrected.tracks[testCase.track]);
      const drawn = trackedMaskPathAt(mask, track, testCase.sourceSeconds).vertices.flatMap(
        (vertex) => [vertex.x, vertex.y, vertex.inX, vertex.inY, vertex.outX, vertex.outY],
      );
      expect(drawn).toHaveLength(testCase.expected.count);
      expect(digest(drawn)).toBe(testCase.expected.sha256);
    },
  );
});
