/*
 * Native entrypoint for a built Capability Pack payload.
 *
 * WHY THIS EXISTS: `uv venv --relocatable` gives every console script a `#!/bin/sh`
 * wrapper that execs `bin/python` next to itself. On macOS a script's code signature is
 * stored in extended attributes, and a pack reaches a user's machine as a ZIP the host
 * extracts file by file, which carries no extended attributes. The host's executable-trust
 * check (`codesign --verify` on the signed entrypoint) could therefore never pass on the
 * wrapper, however correctly the release job signed it. A Mach-O carries its signature
 * inside the file, so this launcher's signature survives the ZIP.
 *
 * It does exactly what uv's wrapper did, and nothing more:
 *   - resolve its own real path (following links, as `realpath "$0"` did);
 *   - exec the interpreter `python` in that same directory;
 *   - run the console-script target `from <module> import <function>; sys.exit(<function>())`;
 *   - forward every argument unchanged and inherit the environment unchanged.
 * The one deliberate difference is `-P`: `python -c` would put the CURRENT DIRECTORY at the
 * front of `sys.path`, letting whatever directory the host happens to launch from shadow the
 * worker's modules. uv's wrapper put the (module-free) `bin/` directory there instead.
 *
 * The console-script target is baked in at compile time through FP_PYTHON_CODE, generated by
 * scripts/build-capability-pack.sh from the wrapper it replaces, so the signature covers it.
 */
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#ifdef __APPLE__
#include <mach-o/dyld.h>
#endif

#ifndef FP_PYTHON_CODE
#error "FP_PYTHON_CODE must name the console-script code; build with scripts/build-capability-pack.sh"
#endif

static const char INTERPRETER_NAME[] = "python";
static const int EXIT_CANNOT_EXECUTE = 126;
static const int EXIT_NOT_FOUND = 127;

/* Absolute, link-resolved path of this running executable, or -1. `out` holds PATH_MAX. */
static int resolve_own_path(char *out) {
#ifdef __APPLE__
  char raw[PATH_MAX];
  uint32_t size = sizeof raw;
  if (_NSGetExecutablePath(raw, &size) != 0) {
    errno = ENAMETOOLONG;
    return -1;
  }
  return realpath(raw, out) == NULL ? -1 : 0;
#elif defined(__linux__)
  return realpath("/proc/self/exe", out) == NULL ? -1 : 0;
#else
#error "unsupported platform: the pack launcher resolves its path on macOS and Linux only"
#endif
}

int main(int argc, char **argv) {
  char own_path[PATH_MAX];
  if (resolve_own_path(own_path) != 0) {
    fprintf(stderr, "framepilot pack launcher: cannot resolve its own path: %s\n", strerror(errno));
    return EXIT_NOT_FOUND;
  }
  char *separator = strrchr(own_path, '/');
  if (separator == NULL) {
    fprintf(stderr, "framepilot pack launcher: resolved path %s has no directory\n", own_path);
    return EXIT_NOT_FOUND;
  }
  size_t directory_length = (size_t)(separator - own_path) + 1;
  char interpreter[PATH_MAX];
  if (directory_length + sizeof INTERPRETER_NAME > sizeof interpreter) {
    fprintf(stderr, "framepilot pack launcher: interpreter path is too long\n");
    return EXIT_NOT_FOUND;
  }
  memcpy(interpreter, own_path, directory_length);
  memcpy(interpreter + directory_length, INTERPRETER_NAME, sizeof INTERPRETER_NAME);

  /* interpreter -P -c CODE <every original argument after argv[0]> NULL */
  const int fixed_arguments = 4;
  char **child_argv = calloc((size_t)argc + (size_t)fixed_arguments, sizeof *child_argv);
  if (child_argv == NULL) {
    fprintf(stderr, "framepilot pack launcher: out of memory\n");
    return EXIT_CANNOT_EXECUTE;
  }
  child_argv[0] = interpreter;
  child_argv[1] = "-P";
  child_argv[2] = "-c";
  child_argv[3] = FP_PYTHON_CODE;
  for (int index = 1; index < argc; index += 1) child_argv[fixed_arguments + index - 1] = argv[index];

  execv(interpreter, child_argv);
  int failure = errno;
  fprintf(stderr, "framepilot pack launcher: cannot run %s: %s\n", interpreter, strerror(failure));
  free(child_argv);
  return failure == ENOENT ? EXIT_NOT_FOUND : EXIT_CANNOT_EXECUTE;
}
