"""BR0.4 pilot set: construction-true clips (ground-truth alpha exists by construction).

NOT the labelled pilot set of MO-8. 06-PRECISION-AND-EVAL allows construction-true clips:
a subject with real (fractional) alpha is composited over moving backgrounds, so the ground
truth is exact. Subjects are synthetic articulated figures rendered here with supersampling
(anti-aliased edges, sub-pixel hair strands) and temporal supersampling (true motion-blur
alpha). Backgrounds are real rendered imagery: still frames of Sintel (Blender Foundation,
CC-BY 3.0), panned/shaken/darkened per category.

Licences: subjects = generated by this script (no third-party content); backgrounds =
Sintel, CC-BY 3.0, (c) Blender Foundation | durian.blender.org.

Output per clip in .cache/pilot/<name>/: frames.mkv (FFV1 rgb24, lossless), gt_alpha.npz
(uint8, T×H×W), meta.json (category, click, licence).
"""

from __future__ import annotations

import json
import math
import subprocess
from dataclasses import dataclass, field

import cv2
import numpy as np

import common

W, H = 1920, 1080
FPS = 24
FRAMES = 32  # bounded by CPU-EP compute on the 16 GB machine (BR0.7)
SS = 4  # spatial supersampling for subject rendering
PILOT_DIR = common.CACHE / "pilot"
BG_DIR = common.MEDIA / "bg"
SINTEL_BG = {
    "bg_000110": "00:01:10", "bg_000330": "00:03:30", "bg_000440": "00:04:40",
    "bg_000550": "00:05:50", "bg_001130": "00:11:30",
}
LICENCE_BG = "Sintel still frames, (c) Blender Foundation | durian.blender.org, CC-BY 3.0"


@dataclass
class Figure:
    height: float  # px, feet to crown
    colours: dict  # part -> BGR-less RGB tuple (0..255)
    hair: int = 60  # strands
    hair_len: float = 0.18  # × height
    head_scale: float = 1.0
    seed: int = 0
    texture: np.ndarray = field(default=None, repr=False)


def ensure_backgrounds() -> None:
    BG_DIR.mkdir(parents=True, exist_ok=True)
    for name, t in SINTEL_BG.items():
        p = BG_DIR / f"{name}.png"
        if not p.exists():
            subprocess.run(["ffmpeg", "-nostdin", "-loglevel", "error", "-ss", t, "-i",
                            "https://download.blender.org/durian/movies/Sintel.2010.1080p.mkv", "-frames:v", "1",
                            "-y", str(p)], check=True)


def load_bg(name: str, scale: float = 1.45) -> np.ndarray:
    img = cv2.cvtColor(cv2.imread(str(BG_DIR / f"{name}.png")), cv2.COLOR_BGR2RGB)
    img = img[int(img.shape[0] * 0.12) : int(img.shape[0] * 0.88)]  # drop letterbox bars
    s = max(scale, (H + 40) / img.shape[0])
    return cv2.resize(img, None, fx=s, fy=s, interpolation=cv2.INTER_CUBIC).astype(np.float32) / 255.0


def bg_frame(bg: np.ndarray, x: float, y: float) -> np.ndarray:
    m = np.float32([[1, 0, -x], [0, 1, -y]])
    return cv2.warpAffine(bg, m, (W, H), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT)


def _capsule(p0, p1, r):
    (x0, y0), (x1, y1) = p0, p1
    ang = math.degrees(math.atan2(y1 - y0, x1 - x0))
    length = math.hypot(x1 - x0, y1 - y0)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    return ((cx, cy), (length / 2 + r, r), ang)


def render_figure(fig: Figure, x: float, y: float, phase: float, sway: float = 0.0):
    """Premultiplied RGB and alpha (float32, full frame) of a figure whose feet centre is (x, y)."""
    h = fig.height
    pad = int(h * 0.45)
    bx0, by0 = max(int(x - pad), 0), max(int(y - h - pad * 0.6), 0)
    bx1, by1 = min(int(x + pad), W), min(int(y + pad * 0.6), H)
    if bx1 <= bx0 or by1 <= by0:
        return np.zeros((H, W, 3), np.float32), np.zeros((H, W), np.float32)
    bw, bh = bx1 - bx0, by1 - by0
    ss = SS if bw * bh <= 700_000 else 3  # bound the supersampled canvas (~300 MB worst case)
    ss_w, ss_h = bw * ss, bh * ss
    rgb = np.zeros((ss_h, ss_w, 3), np.float32)
    alpha = np.zeros((ss_h, ss_w), np.float32)

    def P(px, py):  # frame px -> supersampled local coords
        return ((px - bx0) * ss, (py - by0) * ss)

    swing = math.sin(phase) * 0.45
    hip = (x, y - 0.47 * h)
    neck = (x + sway * 0.05 * h, y - 0.82 * h)
    head_r = 0.075 * h * fig.head_scale
    head = (neck[0] + sway * 0.02 * h, neck[1] - head_r * 1.1)
    leg_l = 0.47 * h
    arm_l = 0.36 * h
    parts = [
        ("legs", hip, (hip[0] + math.sin(swing) * leg_l, hip[1] + math.cos(swing) * leg_l), 0.045 * h),
        ("legs", hip, (hip[0] - math.sin(swing) * leg_l, hip[1] + math.cos(swing) * leg_l), 0.045 * h),
        ("torso", hip, neck, 0.10 * h),
        ("arms", (neck[0], neck[1] + 0.03 * h), (neck[0] - math.sin(swing) * arm_l, neck[1] + math.cos(swing) * arm_l), 0.03 * h),
        ("arms", (neck[0], neck[1] + 0.03 * h), (neck[0] + math.sin(swing) * arm_l, neck[1] + math.cos(swing) * arm_l), 0.03 * h),
    ]
    for part, a, b, r in parts:
        (cx, cy), (ax, ay), ang = _capsule(P(*a), P(*b), r * ss)
        m = np.zeros((ss_h, ss_w), np.uint8)
        cv2.ellipse(m, ((cx, cy), (2 * ax, 2 * ay), ang), 255, -1, cv2.LINE_8)
        sel = m > 0
        rgb[sel] = np.array(fig.colours[part], np.float32) / 255.0
        alpha[sel] = 1.0
    hc = P(*head)
    m = np.zeros((ss_h, ss_w), np.uint8)
    cv2.circle(m, (int(hc[0]), int(hc[1])), int(head_r * ss), 255, -1)
    sel = m > 0
    rgb[sel] = np.array(fig.colours["head"], np.float32) / 255.0
    alpha[sel] = 1.0
    # Texture (moves with the figure): multiplicative luminance noise.
    # Texture fixed to the figure (not the canvas): a noise field in figure-local units, sampled
    # at this canvas's offset, so it moves with the figure when the canvas is clipped.
    if fig.texture is None:
        rng = np.random.default_rng(fig.seed)
        fig.texture = rng.uniform(0.7, 1.15, (64, 64)).astype(np.float32)
    ys = (np.arange(ss_h, dtype=np.float32) / ss + by0 - (y - h)) / (h / 40.0)
    xs = (np.arange(ss_w, dtype=np.float32) / ss + bx0 - (x - pad)) / (h / 40.0)
    tex = cv2.remap(fig.texture, *np.meshgrid(xs, ys), interpolation=cv2.INTER_CUBIC, borderMode=cv2.BORDER_WRAP)
    rgb *= tex[..., None]
    # Hair: thin strands (1 supersampled px = 1/4 frame px) with their own colour.
    if fig.hair:
        rng = np.random.default_rng(fig.seed + 1)
        hm = np.zeros((ss_h, ss_w), np.uint8)
        L = fig.hair_len * h * ss
        for i in range(fig.hair):
            a0 = math.pi * (1.05 + 0.9 * i / max(fig.hair - 1, 1))  # over the crown
            sx = hc[0] + math.cos(a0) * head_r * ss * 0.95
            sy = hc[1] + math.sin(a0) * head_r * ss * 0.95
            pts = [(sx, sy)]
            ang = a0 + rng.uniform(-0.3, 0.3)
            for s in range(12):
                ang += 0.12 * math.sin(phase * 0.7 + i * 0.37 + s * 0.4) + sway * 0.05
                sx += math.cos(ang) * L / 12
                sy += math.sin(ang) * L / 12 + L / 60 * s * 0.4
                pts.append((sx, sy))
            cv2.polylines(hm, [np.int32(pts)], False, 255, thickness=int(rng.integers(1, 3)), lineType=cv2.LINE_8)
        hsel = hm > 0
        rgb[hsel] = np.array(fig.colours["hair"], np.float32) / 255.0
        alpha[hsel] = 1.0
    # Area-downsample: fractional alpha on every edge; premultiply first.
    prem = cv2.resize(rgb * alpha[..., None], (bw, bh), interpolation=cv2.INTER_AREA)
    a = cv2.resize(alpha, (bw, bh), interpolation=cv2.INTER_AREA)
    full_p = np.zeros((H, W, 3), np.float32)
    full_a = np.zeros((H, W), np.float32)
    full_p[by0:by1, bx0:bx1] = prem
    full_a[by0:by1, bx0:bx1] = a
    return full_p, full_a


def render_blurred(fig, path_fn, t, samples):
    """Temporal supersampling over a 180° shutter: true motion-blur alpha."""
    acc_p = np.zeros((H, W, 3), np.float32)
    acc_a = np.zeros((H, W), np.float32)
    for s in range(samples):
        x, y, phase, sway = path_fn(t + ((s + 0.5) / samples - 0.5) * 0.5)
        p, a = render_figure(fig, x, y, phase, sway)
        acc_p += p
        acc_a += a
    return acc_p / samples, acc_a / samples


def over(fg_p, fg_a, bg):
    return fg_p + (1.0 - fg_a[..., None]) * bg


def palette(seed, base):
    rng = np.random.default_rng(seed)
    jit = lambda c: tuple(int(np.clip(v + rng.integers(-25, 25), 0, 255)) for v in c)  # noqa: E731
    return {k: jit(v) for k, v in base.items()}


PERSON = {"head": (225, 180, 150), "hair": (60, 35, 20), "torso": (40, 90, 170), "arms": (225, 180, 150),
          "legs": (50, 50, 60)}
EARTHY = {"head": (170, 110, 80), "hair": (120, 70, 40), "torso": (150, 95, 65), "arms": (170, 115, 85),
          "legs": (110, 70, 50)}


def clip_specs():
    walk = lambda x0, vx, y, cadence=0.35: (lambda t: (x0 + vx * t, y, t * cadence, 0.0))  # noqa: E731
    return {
        "walk_pan": dict(bg="bg_000330", bg_path=lambda t: (200 + 6 * t, 60), subject=(Figure(760, palette(1, PERSON), seed=1), walk(600, 9, 1000)), blur=2),
        "hair_busy": dict(bg="bg_000110", bg_path=lambda t: (300 + 2 * t, 80 + 1.5 * math.sin(t / 5)),
                          subject=(Figure(1500, palette(2, PERSON), hair=260, hair_len=0.22, head_scale=1.6, seed=2),
                                   lambda t: (960 + 60 * math.sin(t / 9), 1650, 0.2, math.sin(t / 6))), blur=2),
        "similar_colour": dict(bg="bg_001130", bg_path=lambda t: (400 + 4 * t, 120), subject=(Figure(700, palette(3, EARTHY), seed=3), walk(500, 10, 1020)), blur=2),
        "crossing": dict(bg="bg_000440", bg_path=lambda t: (300, 100), subject=(Figure(720, palette(4, PERSON), seed=4), walk(900, 2, 1000)),
                         occluder=(Figure(760, palette(40, {**PERSON, "torso": (160, 40, 40)}), seed=40), walk(1700, -28, 1040)), blur=2),
        "leave_reenter": dict(bg="bg_000330", bg_path=lambda t: (500, 80),
                              subject=(Figure(700, palette(5, PERSON), seed=5),
                                       lambda t: (1500 + 520 * math.sin(t * math.pi / 30), 1000, t * 0.4, 0.0)), blur=2),
        "fast_motion": dict(bg="bg_000550", bg_path=lambda t: (100 + 25 * t, 60), subject=(Figure(740, palette(6, PERSON), seed=6), walk(250, 32, 1010, 0.6)), blur=6),
        "twin_distractor": dict(bg="bg_000440", bg_path=lambda t: (500 + 3 * t, 100), subject=(Figure(720, palette(7, PERSON), seed=7), walk(700, 12, 1000)),
                                behind=(Figure(720, palette(7, PERSON), seed=8), walk(1450, -10, 990)), blur=2),
        "low_light": dict(bg="bg_000330", bg_path=lambda t: (700 - 4 * t, 60), subject=(Figure(760, palette(9, EARTHY), seed=9), walk(1300, -11, 1010)),
                          blur=2, gain=0.22, noise=0.03),
    }


def render_clip(name: str, spec: dict) -> None:
    out = PILOT_DIR / name
    out.mkdir(parents=True, exist_ok=True)
    bg = load_bg(spec["bg"])
    fig, path = spec["subject"]
    gt = np.zeros((FRAMES, H, W), np.uint8)
    rng = np.random.default_rng(99)
    enc = subprocess.Popen(["ffmpeg", "-nostdin", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "rgb24", "-s",
                            f"{W}x{H}", "-r", str(FPS), "-i", "-", "-c:v", "ffv1", "-y", str(out / "frames.mkv")],
                           stdin=subprocess.PIPE)
    click = None
    for t in range(FRAMES):
        frame = bg_frame(bg, *spec["bg_path"](t))
        if "behind" in spec:
            bfig, bpath = spec["behind"]
            bp, ba = render_blurred(bfig, bpath, t, spec["blur"])
            frame = over(bp, ba, frame)
        sp, sa = render_blurred(fig, path, t, spec["blur"])
        frame = over(sp, sa, frame)
        vis = sa
        if "occluder" in spec:
            ofig, opath = spec["occluder"]
            op_, oa = render_blurred(ofig, opath, t, spec["blur"])
            frame = over(op_, oa, frame)
            vis = sa * (1.0 - oa)
        if "gain" in spec:
            frame = frame * spec["gain"] + rng.normal(0, spec["noise"], frame.shape).astype(np.float32)
        gt[t] = np.clip(np.round(vis * 255), 0, 255).astype(np.uint8)
        if t == 0:
            dist = cv2.distanceTransform((vis > 0.5).astype(np.uint8), cv2.DIST_L2, 5)
            yx = np.unravel_index(int(np.argmax(dist)), dist.shape)
            click = [float(yx[1]), float(yx[0])]
        enc.stdin.write((np.clip(frame, 0, 1) * 255 + 0.5).astype(np.uint8).tobytes())
    enc.stdin.close()
    enc.wait()
    np.savez_compressed(out / "gt_alpha.npz", alpha=gt)
    (out / "meta.json").write_text(json.dumps({
        "name": name, "frames": FRAMES, "fps": FPS, "width": W, "height": H, "click": click, "clickLabel": 1,
        "background": spec["bg"], "licence": {"subject": "generated (pilot_generate.py)", "background": LICENCE_BG},
        "foregroundFractionMean": round(float((gt > 127).mean()), 4),
    }, indent=2))
    print(name, "click", click, "fg", round(float((gt > 127).mean()), 4), flush=True)


def main() -> None:
    import sys

    ensure_backgrounds()
    names = sys.argv[1:] or list(clip_specs())
    specs = clip_specs()
    for n in names:
        render_clip(n, specs[n])


if __name__ == "__main__":
    main()
