/** Typed IPC channel registry between Electron main and the renderer. */
export const IpcChannels = {
  ping: 'framepilot:ping',
  licenseStatus: 'framepilot:license:status',
  licenseActivate: 'framepilot:license:activate',
  licenseDeactivate: 'framepilot:license:deactivate',
  sidecarStatus: 'framepilot:sidecar:status',
  projectOpen: 'framepilot:project:open',
  projectSnapshot: 'framepilot:project:snapshot',
  projectOpenDialog: 'framepilot:project:open-dialog',
  projectSave: 'framepilot:project:save',
  projectSaveDefault: 'framepilot:project:save-default',
  projectCommitPatch: 'framepilot:project:commit-patch',
  projectsDir: 'framepilot:project:dir',
  projectReveal: 'framepilot:project:reveal',
  projectRecent: 'framepilot:project:recent',
  renderExport: 'framepilot:render:export',
  renderExportStart: 'framepilot:render:export-start',
  renderExportCancel: 'framepilot:render:export-cancel',
  renderExportProgress: 'framepilot:render:export-progress',
  exportSaveAs: 'framepilot:export:save-as',
  /** Historical whole-file/framed compatibility channel. */
  mediaImport: 'framepilot:media:import',
  /** Production bounded media data plane with first-class ordering metadata. */
  mediaImportChunk: 'framepilot:media:import-chunk',
  mediaImportAsset: 'framepilot:media:import-asset',
  transcribe: 'framepilot:ai:transcribe',
  aiChat: 'framepilot:ai:chat',
  aiPlan: 'framepilot:ai:plan',
  aiEdit: 'framepilot:ai:edit',
  projectChanged: 'framepilot:project:changed',
  conversationsList: 'framepilot:conversations:list',
  conversationsLoad: 'framepilot:conversations:load',
  conversationsSave: 'framepilot:conversations:save',
  conversationsDelete: 'framepilot:conversations:delete',
  aiStreamStart: 'framepilot:ai:stream-start',
  aiStreamAbort: 'framepilot:ai:stream-abort',
  aiStreamEvent: 'framepilot:ai:stream-event',
  aiStreamAnswer: 'framepilot:ai:stream-answer',
  runStart: 'framepilot:run:start',
  runCommand: 'framepilot:run:command',
  runSnapshot: 'framepilot:run:snapshot',
  runSubscribe: 'framepilot:run:subscribe',
  runUnsubscribe: 'framepilot:run:unsubscribe',
  runAck: 'framepilot:run:ack',
  runEvent: 'framepilot:run:event',
  aiProviders: 'framepilot:ai:providers',
  aiConfigGet: 'framepilot:ai:config-get',
  aiConfigSet: 'framepilot:ai:config-set',
  visualIndex: 'framepilot:visual-index',
  capabilityPackStorage: 'framepilot:capability-pack:storage',
  capabilityPackRelocate: 'framepilot:capability-pack:relocate',
  capabilityPackRelocationProgress: 'framepilot:capability-pack:relocation-progress',
  capabilityPackPropose: 'framepilot:capability-pack:propose',
  capabilityPackProposeProjectDependency: 'framepilot:capability-pack:propose-project-dependency',
  capabilityPackProjectStatus: 'framepilot:capability-pack:project-status',
  capabilityPackInstall: 'framepilot:capability-pack:install',
  capabilityPackCancel: 'framepilot:capability-pack:cancel',
  capabilityPackPlanEviction: 'framepilot:capability-pack:plan-eviction',
  capabilityPackExecuteEviction: 'framepilot:capability-pack:execute-eviction',
  capabilityPackProgress: 'framepilot:capability-pack:progress',
  capabilityPackTrack: 'framepilot:capability-pack:track',
  capabilityPackCancelTrack: 'framepilot:capability-pack:cancel-track',
  capabilityPackTrackProgress: 'framepilot:capability-pack:track-progress',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];

export type {
  TrackingProgressWire,
  TrackingRequestIntentWire,
  TrackingRunResultWire,
  SidecarPhase,
  SidecarStatus,
  RecentProject,
  ProjectChangedEvent,
  ProjectOpenResult,
  ProjectSaveResult,
  ProjectPatchCommitRequest,
  ProjectPatchCommitResult,
  RevealResult,
  ExportRequest,
  ExportResult,
  ExportJobStatus,
  ExportProgressMessage,
  ExportSaveAsRequest,
  ExportSaveAsResult,
  MediaImportRequest,
  MediaImportResult,
  ImportAssetRequest,
  ImportAssetResult,
  AsrProviderName,
  TranscriptionRequest,
  TranscriptionResult,
  TranscriptionWord,
  AiRequest,
  AiTextResult,
  AiEditResult,
  ConversationSummary,
  ConversationRecord,
  ConversationSaveResult,
  AiStreamMode,
  AiStreamRequest,
  AiStreamHistoryMessage,
  AiStreamSelection,
  AiStreamInteractionContext,
  AiStreamUserMemory,
  AiStreamAgentOptions,
  AiStreamEventMessage,
  AiStreamAnswerMessage,
  DurableRunCommandKind,
  DurableRunStartRequest,
  DurableRunCommandRequest,
  DurableRunCommandEnvelope,
  DurableRunEvent,
  DurableRunStatus,
  DurableRunSnapshot,
  DurableRunAccepted,
  DurableRunSnapshotRequest,
  DurableRunSubscribeRequest,
  DurableRunSubscription,
  DurableRunEventMessage,
  DurableRunAckRequest,
  AiProviderName,
  AiProviderInfo,
  AiConfig,
  AiConfigUpdate,
  VisualIndexRequest,
  VisualIndexResult,
  CapabilityPackIdentityWire,
  CapabilityPackStorageSnapshotWire,
  CapabilityPackInstallProposalWire,
  CapabilityPackInstallApprovalWire,
  CapabilityPackActionResultWire,
  CapabilityPackProposalResultWire,
  CapabilityPackInstallStartResultWire,
  CapabilityPackEvictionPlanWire,
  CapabilityPackEvictionPlanResultWire,
  CapabilityPackEvictionApprovalWire,
  CapabilityPackProgressWire,
  CapabilityPackRelocationProgressWire,
  CapabilityPackRelocationResultWire,
  CapabilityPackProjectPinWire,
  CapabilityPackProjectDependencyWire,
  CapabilityPackProjectResolutionWire,
  LicenseStatus,
  LicenseStatusKind,
  LicenseActivateRequest,
  FramePilotBridge,
} from '@framepilot/shared-types';
