/**
 * PX5 — performance evidence for the layer compositor on the Scale row (plan
 * `plan/background-removal-ai/09-PREVIEW-EXPORT-PARITY.md`, "PX5 — performance evidence";
 * numbers in `plan/background-removal-ai/PX5-BUDGETS.md`).
 *
 * The row: a 3-minute 4K timeline with 4 picture layers + text + a 4K matte, generated by
 * `pnpm px5:fixture` into `tests/e2e/.tmp-px5-scale/` (never committed). Each run loads one
 * variant of it into the real editor, plays it through the real transport, seeks it, and reads
 * **the engine's own telemetry** (`LayerPreviewEngine.debugTelemetry()`, PX5.1). Nothing here
 * times the page from outside.
 *
 * Two kinds of assertion, because this runs on two kinds of machine:
 *
 *  - **Invariants** (always): properties of the algorithm, identical on a GPU and on CI's CPU GL
 *    (SwiftShader). Live decoders never exceed the pool's cap; the picture cache never exceeds
 *    its byte budget plus what one decode-ahead window pins; the GL pools stop growing once the
 *    timeline is steady; load shedding never removes a layer. A slow machine cannot fail these.
 *  - **Budgets** (`PX5_ASSERT=budgets`, real hardware only): <= 1% dropped frames and
 *    seek-to-present p95 <= 100 ms. CI has no GPU and two cores, so a wall-clock budget there
 *    would measure the runner; CI logs the numbers and does not gate on them.
 *
 * Runs only with FRAMEPILOT_RUN_PERF=1. **One variant at a time on a workstation**, under the
 * footprint watchdog (`workers/smart-mask/spike/watchdog.py`):
 *
 *   FRAMEPILOT_RUN_PERF=1 PX5_ASSERT=budgets pnpm --filter @framepilot/e2e exec playwright test \
 *     --project=preview-perf --grep 'scale/proxy'
 *
 * Media is served by the dev server itself (`/@fs/`): same origin, and it honours `Range`, which
 * the decode worker needs for the 4K files (they are larger than its whole-file limit).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test, type Page } from '@playwright/test';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');
const FIXTURE = join(REPO, 'tests', 'e2e', '.tmp-px5-scale');
const RESULTS_DIR = join(FIXTURE, 'results');
const RUN = process.env.FRAMEPILOT_RUN_PERF === '1';
const ASSERT_BUDGETS = process.env.PX5_ASSERT === 'budgets';
const PLAY_SECONDS = Number(process.env.PX5_PLAY_SECONDS ?? 20);
const SEEKS = Number(process.env.PX5_SEEKS ?? 24);

/** PX5 budgets (09). Never raised here; a miss is recorded in PX5-BUDGETS.md. */
const MAX_DROPPED_SHARE = 0.01;
const MAX_SEEK_TO_PRESENT_P95_MS = 100;
/** `MAX_LIVE_DECODERS` of `decode/decoder-pool.ts`. */
const DECODER_POOL_CAPACITY = 6;
/** `CACHE_BUDGET_BYTES` of `layer-preview-engine.ts`. */
const CACHE_BUDGET_BYTES = 384 * 1024 * 1024;
/**
 * What eviction may not take: the pictures and matte frames of the decode-ahead window
 * (`LOOKAHEAD_FRAMES` + 1 project frames) plus one in-flight decode window per source
 * (`DECODE_WINDOW`). Bounded by the timeline, not by how long it plays.
 */
const PINNED_FRAMES = 13 + 8;

interface ChannelSummary {
  count: number;
  p50: number;
  p95: number;
  p99: number;
  max: number;
}
interface Telemetry {
  channels: Record<
    | 'frameInterval'
    | 'composite'
    | 'seekToPresent'
    | 'exactComposite'
    | 'maskRaster'
    | 'keyStack'
    | 'decode',
    ChannelSummary
  >;
  playback: {
    expectedFrames: number;
    presentedFrames: number;
    droppedFrames: number;
    droppedShare: number;
    missingTicks: number;
    renderScaleChanges: number;
    lowestRenderScale: number;
  };
  gauges: Record<
    'pictureCacheBytes' | 'glPoolBytes' | 'glPoolTargets' | 'liveDecoders',
    { current: number; peak: number }
  >;
  maskRasterCacheHits: number;
  gpuSync: boolean;
}
interface EngineHook {
  debugStats(): Record<string, number>;
  debugTelemetry(): Promise<Telemetry>;
  debugPresentedFrame(): { projectTimeSec: number; layers: unknown[] };
  seek(t: number): Promise<void>;
  telemetry: { reset(): void; gpuSync: boolean };
}
type ScaleProject = {
  id: string;
  name: string;
  fps: number;
  assets: { id: string; path: string; media?: { proxyPath?: string } }[];
  timeline: { tracks: { clips: { masks?: { kind: string; artifact?: { key: string } }[] }[] }[] };
};

type MediaMode = 'proxy' | 'original';

/** variant of the fixture x which media the monitor decodes. `proxy` is the desktop path. */
const RUNS: readonly { variant: string; mode: MediaMode; gpuSync?: boolean }[] = [
  { variant: 'scale', mode: 'proxy' },
  { variant: 'scale-plain', mode: 'proxy' },
  { variant: 'scale-path', mode: 'proxy' },
  { variant: 'scale-path-full', mode: 'proxy' },
  { variant: 'scale-key', mode: 'proxy', gpuSync: true },
  { variant: 'scale-key-nofinesse', mode: 'proxy', gpuSync: true },
  { variant: 'scale-plain', mode: 'original' },
];

const fsUrl = (origin: string, file: string): string =>
  `${origin}/@fs${file.split('/').map(encodeURIComponent).join('/')}`;

async function openScale(page: Page, variant: string, mode: MediaMode): Promise<ScaleProject> {
  const origin = new URL(test.info().project.use.baseURL ?? 'http://127.0.0.1:5173').origin;
  const manifest = JSON.parse(readFileSync(join(FIXTURE, 'manifest.json'), 'utf8')) as {
    matte: { key: string; root: string };
  };
  const project = JSON.parse(
    readFileSync(join(FIXTURE, 'projects', `${variant}.json`), 'utf8'),
  ) as ScaleProject;
  for (const asset of project.assets) {
    const proxy = asset.media?.proxyPath;
    if (asset.media && proxy !== undefined) {
      if (mode === 'proxy') asset.media.proxyPath = fsUrl(origin, join(FIXTURE, proxy));
      else delete asset.media.proxyPath;
    }
    asset.path = fsUrl(origin, join(FIXTURE, asset.path));
  }
  const matteRoot = fsUrl(origin, join(FIXTURE, manifest.matte.root));
  await page.addInitScript((root: string) => {
    (
      window as unknown as { __fpMatteArtifactUrl: (key: string, name: string) => string }
    ).__fpMatteArtifactUrl = (key, name) => `${root}/${key}/${name}`;
  }, matteRoot);
  // A blank same-origin document to seed localStorage from, before the editor ever loads.
  await page.route('**/__px5-blank.html', (route) =>
    route.fulfill({ contentType: 'text/html', body: '<!doctype html><title>px5</title>' }),
  );
  await page.goto(`${origin}/__px5-blank.html`);
  await page.evaluate((p) => {
    localStorage.clear();
    localStorage.setItem(`framepilot:project:${p.id}`, JSON.stringify(p));
    localStorage.setItem('framepilot:last-project-id', p.id);
  }, project);
  await page.goto(`${origin}/`);
  await expect(page.getByLabel('project name')).toHaveText(project.name, { timeout: 60_000 });
  await expect(page.locator('.webcodecs-preview')).toBeVisible({ timeout: 60_000 });
  await expect
    .poll(
      () =>
        page.evaluate(() => {
          const engine = (window as unknown as { __fpPreviewEngine?: EngineHook })
            .__fpPreviewEngine;
          if (!engine || engine.debugStats().segCount === 0) return false;
          return Number.isFinite(engine.debugPresentedFrame().projectTimeSec);
        }),
      { timeout: 180_000, message: 'the monitor never presented its first frame' },
    )
    .toBe(true);
  await expect(page.locator('.webcodecs-preview-error')).toHaveCount(0);
  return project;
}

const snapshot = (page: Page): Promise<Telemetry> =>
  page.evaluate(() =>
    (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine.debugTelemetry(),
  );

test.describe('PX5 Scale row', () => {
  test.skip(!RUN, 'performance evidence runs only with FRAMEPILOT_RUN_PERF=1');
  test.describe.configure({ mode: 'serial' });

  for (const run of RUNS) {
    test(`${run.variant}/${run.mode}`, async ({ page }, testInfo) => {
      test.setTimeout((PLAY_SECONDS + 240) * 1000);
      expect(
        existsSync(join(FIXTURE, 'manifest.json')),
        'no Scale fixture: run `pnpm px5:fixture` first',
      ).toBe(true);
      const problems: string[] = [];
      page.on('console', (message) => {
        if (message.type() === 'error' || message.type() === 'warning') {
          problems.push(`${message.type()}: ${message.text().slice(0, 300)}`);
        }
      });
      page.on('pageerror', (error) => problems.push(`pageerror: ${error.message.slice(0, 300)}`));
      const project = await openScale(page, run.variant, run.mode);

      // --- seek-to-present: deterministic targets spread over the whole timeline ------------
      const duration = await page.evaluate(
        () =>
          (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine.debugStats()
            .durationSec ?? 0,
      );
      await page.evaluate(
        async ({ seeks, durationSec, fps }) => {
          const engine = (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine;
          engine.telemetry.reset();
          // An LCG, so every run seeks the same frames; none lands on a GOP boundary by design.
          let state = 12345;
          for (let i = 0; i < seeks; i++) {
            state = (state * 1103515245 + 12345) % 2147483648;
            const frame = Math.floor((state / 2147483648) * (durationSec - 1) * fps);
            await engine.seek((frame + 0.5) / fps);
          }
        },
        { seeks: SEEKS, durationSec: duration, fps: project.fps },
      );
      const seeking = await snapshot(page);

      // --- frame stepping: consecutive frames, so decode is contiguous and what is left is the
      // steady cost of ONE full-resolution composite of this timeline --------------------------
      await page.evaluate(
        async ({ fps }) => {
          const engine = (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine;
          await engine.seek(60);
          engine.telemetry.reset();
          for (let i = 1; i <= 12; i++) await engine.seek(60 + (i + 0.5) / fps);
        },
        { fps: project.fps },
      );
      const stepping = await snapshot(page);
      // What the row looks like, so a number is never reported for a monitor that drew nothing.
      mkdirSync(RESULTS_DIR, { recursive: true });
      await page
        .locator('.webcodecs-preview-canvas')
        .screenshot({ path: join(RESULTS_DIR, `${run.variant}.${run.mode}.png`) });

      // --- playback through the real transport ----------------------------------------------
      await page.evaluate(
        async ({ gpuSync }) => {
          const engine = (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine;
          await engine.seek(1);
          engine.telemetry.reset();
          engine.telemetry.gpuSync = gpuSync;
        },
        { gpuSync: run.gpuSync === true },
      );
      await page.getByRole('button', { name: 'play', exact: true }).click();
      await page.waitForTimeout((PLAY_SECONDS * 1000) / 2);
      const midway = await snapshot(page);
      await page.waitForTimeout((PLAY_SECONDS * 1000) / 2);
      const layersWhilePlaying = await page.evaluate(
        () =>
          (
            window as unknown as { __fpPreviewEngine: EngineHook }
          ).__fpPreviewEngine.debugPresentedFrame().layers.length,
      );
      // Recorded, not assumed: a transport that stopped by itself under load is a finding.
      const pause = page.getByRole('button', { name: 'pause', exact: true });
      const stillPlaying = await pause.isVisible();
      if (stillPlaying) await pause.click();
      const played = await snapshot(page);

      const result = {
        variant: run.variant,
        mode: run.mode,
        playSeconds: PLAY_SECONDS,
        gl: await page.evaluate(() => {
          const gl = document.createElement('canvas').getContext('webgl2');
          const info = gl?.getExtension('WEBGL_debug_renderer_info');
          return gl && info ? String(gl.getParameter(info.UNMASKED_RENDERER_WEBGL)) : 'unknown';
        }),
        seekToPresent: seeking.channels.seekToPresent,
        seekExactComposite: seeking.channels.exactComposite,
        stepToPresent: stepping.channels.seekToPresent,
        stepExactComposite: stepping.channels.exactComposite,
        stepMaskRaster: stepping.channels.maskRaster,
        playback: played.playback,
        frameInterval: played.channels.frameInterval,
        composite: played.channels.composite,
        maskRaster: played.channels.maskRaster,
        keyStack: played.channels.keyStack,
        decode: played.channels.decode,
        gauges: played.gauges,
        glPoolBytesMidway: midway.gauges.glPoolBytes.current,
        renderScaleChangesMidway: midway.playback.renderScaleChanges,
        layersWhilePlaying,
        gpuSync: played.gpuSync,
        stillPlayingAtEnd: stillPlaying,
        problems: problems.slice(0, 20),
      };
      mkdirSync(RESULTS_DIR, { recursive: true });
      writeFileSync(
        join(RESULTS_DIR, `${run.variant}.${run.mode}.json`),
        `${JSON.stringify(result, null, 1)}\n`,
      );
      console.log(`[PX5] ${JSON.stringify(result)}`);
      await testInfo.attach('px5-result', {
        body: JSON.stringify(result, null, 1),
        contentType: 'application/json',
      });

      // --- invariants: the algorithm's, so the same on any machine ---------------------------
      expect(result.seekToPresent.count, 'every seek reached the monitor').toBe(SEEKS);
      expect(result.playback.expectedFrames, 'playback ran').toBeGreaterThan(
        PLAY_SECONDS * project.fps * 0.5,
      );
      expect(result.gauges.liveDecoders.peak, 'live decoders within the pool').toBeLessThanOrEqual(
        DECODER_POOL_CAPACITY,
      );
      expect(layersWhilePlaying, 'load shedding never removes a layer').toBe(4);
      if (played.playback.renderScaleChanges === midway.playback.renderScaleChanges) {
        expect(
          result.gauges.glPoolBytes.current,
          'the GL pools stop growing on a steady timeline',
        ).toBe(result.glPoolBytesMidway);
      }
      expect(
        result.gauges.pictureCacheBytes.peak,
        'the picture cache is bounded by its budget plus what decode-ahead pins',
      ).toBeLessThanOrEqual(CACHE_BUDGET_BYTES + pinnedBytes(project, run.mode));

      if (ASSERT_BUDGETS) {
        expect(result.playback.droppedShare, 'dropped frames').toBeLessThanOrEqual(
          MAX_DROPPED_SHARE,
        );
        expect(result.seekToPresent.p95, 'seek-to-present p95 (ms)').toBeLessThanOrEqual(
          MAX_SEEK_TO_PRESENT_P95_MS,
        );
      }
    });
  }
});

/** Bytes one decode-ahead window may pin: I420 pictures per layer, and 4K matte + foreground. */
function pinnedBytes(project: ScaleProject, mode: MediaMode): number {
  const [width, height] = mode === 'proxy' ? [960, 540] : [3840, 2160];
  const picture = width * height * 1.5;
  const mattes = project.timeline.tracks
    .flatMap((track) => track.clips)
    .flatMap((clip) => clip.masks ?? [])
    .filter((mask) => mask.kind === 'matte').length;
  const matte = 3840 * 2160 * (1 + 4);
  return PINNED_FRAMES * (project.assets.length * picture + mattes * matte);
}
