/**
 * PX5 — performance evidence for the layer compositor on the Scale row (plan
 * `plan/background-removal-ai/09-PREVIEW-EXPORT-PARITY.md`, "PX5 — performance evidence";
 * numbers in `plan/background-removal-ai/PX5-BUDGETS.md`).
 *
 * The row: a 3-minute 4K timeline with 4 picture layers + text + a 4K matte, generated by
 * `pnpm px5:fixture` into `tests/e2e/.tmp-px5-scale/` (never committed). Each run loads one
 * variant of it into the real editor, plays it through the real transport, seeks it, and reads
 * **the engine's own telemetry** (`LayerPreviewEngine.debugTelemetry()`, PX5.1). Nothing here
 * times the page from outside.
 *
 * Two kinds of assertion, because this runs on two kinds of machine:
 *
 *  - **Invariants** (always): properties of the algorithm, identical on a GPU and on CI's CPU GL
 *    (SwiftShader). Live decoders never exceed the pool's cap; the picture cache never exceeds
 *    its byte budget plus what one decode-ahead window pins; the GL pools stop growing once the
 *    timeline is steady; load shedding never removes a layer. A slow machine cannot fail these.
 *  - **Budgets** (`PX5_ASSERT=budgets`, real hardware only): <= 1% dropped frames and
 *    seek-to-present p95 <= 100 ms. CI has no GPU and two cores, so a wall-clock budget there
 *    would measure the runner; CI logs the numbers and does not gate on them.
 *
 * Runs only with FRAMEPILOT_RUN_PERF=1. **One variant at a time on a workstation**, under the
 * footprint watchdog (`workers/smart-mask/spike/watchdog.py`):
 *
 *   FRAMEPILOT_RUN_PERF=1 PX5_ASSERT=budgets pnpm --filter @framepilot/e2e exec playwright test \
 *     --project=preview-perf --grep 'scale/proxy'
 *
 * Media is served by the dev server itself (`/@fs/`): same origin, and it honours `Range`, which
 * the decode worker needs for the 4K files (they are larger than its whole-file limit).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test, type Page } from '@playwright/test';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');
const FIXTURE = join(REPO, 'tests', 'e2e', '.tmp-px5-scale');
const RESULTS_DIR = join(FIXTURE, 'results');
const RUN = process.env.FRAMEPILOT_RUN_PERF === '1';
const ASSERT_BUDGETS = process.env.PX5_ASSERT === 'budgets';
const PLAY_SECONDS = Number(process.env.PX5_PLAY_SECONDS ?? 20);
const SEEKS = Number(process.env.PX5_SEEKS ?? 24);

/** PX5 budgets (09). Never raised here; a miss is recorded in PX5-BUDGETS.md. */
const MAX_DROPPED_SHARE = 0.01;
const MAX_SEEK_TO_PRESENT_P95_MS = 100;
/** `MAX_LIVE_DECODERS` of `decode/decoder-pool.ts`. */
const DECODER_POOL_CAPACITY = 6;
/** `CACHE_BUDGET_BYTES` of `layer-preview-engine.ts`. */
const CACHE_BUDGET_BYTES = 384 * 1024 * 1024;
/**
 * What eviction may not take: the pictures and matte frames of the decode-ahead window
 * (`LOOKAHEAD_FRAMES` + 1 project frames) plus one in-flight decode window per source
 * (`DECODE_WINDOW`). Bounded by the timeline, not by how long it plays.
 */
const PINNED_FRAMES = 13 + 8;

interface ChannelSummary {
  count: number;
  p50: number;
  p95: number;
  p99: number;
  max: number;
}
interface Telemetry {
  channels: Record<
    | 'frameInterval'
    | 'composite'
    | 'seekToPresent'
    | 'exactComposite'
    | 'maskRaster'
    | 'keyStack'
    | 'matteStack'
    | 'decode'
    | 'matteDecode',
    ChannelSummary
  >;
  playback: {
    expectedFrames: number;
    presentedFrames: number;
    droppedFrames: number;
    droppedShare: number;
    missingTicks: number;
    renderScaleChanges: number;
    lowestRenderScale: number;
  };
  gauges: Record<
    'pictureCacheBytes' | 'glPoolBytes' | 'glPoolTargets' | 'liveDecoders',
    { current: number; peak: number }
  >;
  maskRasterCacheHits: number;
  gpuSync: boolean;
}
interface EngineHook {
  debugStats(): Record<string, number>;
  debugTelemetry(): Promise<Telemetry>;
  debugPresentedFrame(): { projectTimeSec: number; layers: unknown[] };
  debugPresentedMattes?(): { tier?: string | null; fromTier?: boolean; state?: string }[];
  seek(t: number): Promise<void>;
  telemetry: { reset(): void; gpuSync: boolean };
  /** PX5.7: the monitor's open stages and the decode worker's report, for a hang. */
  debugInFlight?(): Promise<unknown>;
}
type ScaleProject = {
  id: string;
  name: string;
  fps: number;
  assets: { id: string; path: string; media?: { proxyPath?: string } }[];
  timeline: { tracks: { clips: { masks?: { kind: string; artifact?: { key: string } }[] }[] }[] };
};

type MediaMode = 'proxy' | 'original';

/** variant of the fixture x which media the monitor decodes. `proxy` is the desktop path. */
const RUNS: readonly { variant: string; mode: MediaMode; gpuSync?: boolean }[] = [
  { variant: 'scale', mode: 'proxy' },
  { variant: 'scale-plain', mode: 'proxy' },
  { variant: 'scale-path', mode: 'proxy' },
  { variant: 'scale-path-full', mode: 'proxy' },
  { variant: 'scale-key', mode: 'proxy', gpuSync: true },
  { variant: 'scale-key-nofinesse', mode: 'proxy', gpuSync: true },
  { variant: 'scale-plain', mode: 'original' },
];

const fsUrl = (origin: string, file: string): string =>
  `${origin}/@fs${file.split('/').map(encodeURIComponent).join('/')}`;

async function openScale(page: Page, variant: string, mode: MediaMode): Promise<ScaleProject> {
  const origin = new URL(test.info().project.use.baseURL ?? 'http://127.0.0.1:5173').origin;
  const manifest = JSON.parse(readFileSync(join(FIXTURE, 'manifest.json'), 'utf8')) as {
    matte: { key: string; root: string };
    /** PX5.3: the matte's monitor tier, when the fixture has one. */
    tier?: { root: string; size: [number, number] };
  };
  const project = JSON.parse(
    readFileSync(join(FIXTURE, 'projects', `${variant}.json`), 'utf8'),
  ) as ScaleProject;
  for (const asset of project.assets) {
    const proxy = asset.media?.proxyPath;
    if (asset.media && proxy !== undefined) {
      if (mode === 'proxy') asset.media.proxyPath = fsUrl(origin, join(FIXTURE, proxy));
      else delete asset.media.proxyPath;
    }
    asset.path = fsUrl(origin, join(FIXTURE, asset.path));
  }
  const matteRoot = fsUrl(origin, join(FIXTURE, manifest.matte.root));
  // PX5.3: the desktop reads a monitor tier beside the artifact when one exists. PX5_TIER=0
  // measures the masters-only path (the "before" of the tier).
  const tierRoot =
    manifest.tier !== undefined && process.env.PX5_TIER !== '0'
      ? fsUrl(origin, join(FIXTURE, manifest.tier.root))
      : null;
  await page.addInitScript(
    ({ root, tiers }: { root: string; tiers: string | null }) => {
      const host = window as unknown as {
        __fpMatteArtifactUrl: (key: string, name: string) => string;
        __fpMatteTierUrl?: (key: string, name: string) => string;
      };
      host.__fpMatteArtifactUrl = (key, name) => `${root}/${key}/${name}`;
      if (tiers !== null) host.__fpMatteTierUrl = (key, name) => `${tiers}/${key}/${name}`;
    },
    { root: matteRoot, tiers: tierRoot },
  );
  // A blank same-origin document to seed localStorage from, before the editor ever loads.
  await page.route('**/__px5-blank.html', (route) =>
    route.fulfill({ contentType: 'text/html', body: '<!doctype html><title>px5</title>' }),
  );
  await page.goto(`${origin}/__px5-blank.html`);
  await page.evaluate((p) => {
    localStorage.clear();
    localStorage.setItem(`framepilot:project:${p.id}`, JSON.stringify(p));
    localStorage.setItem('framepilot:last-project-id', p.id);
  }, project);
  await page.goto(`${origin}/`);
  await expect(page.getByLabel('project name')).toHaveText(project.name, { timeout: 60_000 });
  await expect(page.locator('.webcodecs-preview')).toBeVisible({ timeout: 60_000 });
  await expect
    .poll(
      () =>
        page.evaluate(() => {
          const engine = (window as unknown as { __fpPreviewEngine?: EngineHook })
            .__fpPreviewEngine;
          if (!engine || engine.debugStats().segCount === 0) return false;
          return Number.isFinite(engine.debugPresentedFrame().projectTimeSec);
        }),
      { timeout: 180_000, message: 'the monitor never presented its first frame' },
    )
    .toBe(true);
  await expect(page.locator('.webcodecs-preview-error')).toHaveCount(0);
  return project;
}

const snapshot = (page: Page): Promise<Telemetry> =>
  page.evaluate(() =>
    (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine.debugTelemetry(),
  );

/**
 * PX5.7: a step still running this long before the test's own timeout is reported as a hang:
 * the monitor's open stages and the decode worker's own report (`debugInFlight`) are read while
 * the page is still alive, written beside the results, and the test fails naming the stage.
 * About one watched run in ten used to stop inside a `page.evaluate` until the timeout, and a
 * timeout alone says nothing about which promise never settled.
 */
const HANG_REPORT_RESERVE_MS = 25_000;
/** How long the hang report itself may take (a blocked main thread never answers). */
const HANG_REPORT_TIMEOUT_MS = 10_000;

/** What one guarded step of a run needs to know about the run. */
interface RunWatch {
  readonly page: Page;
  /** `variant.mode`, the results file stem. */
  readonly name: string;
  readonly deadlineAt: number;
  readonly problems: readonly string[];
  /** Resolves, with what happened, when the page's code is replaced mid-run (PX5.7). */
  readonly codeReplaced: Promise<string>;
}

/**
 * PX5.7, the cause of the "one run in ten" hang: the dev server hot-updated or reloaded the
 * editor when a file in the worktree changed during the run (another agent's edit), rebuilding
 * the engine under a running step. Whatever is measured after that is not the run it claims to
 * be, so the step fails at once, saying so, instead of waiting for a replaced worker.
 */
function codeReplacement(message: string): boolean {
  return message.startsWith('[vite] hot updated') || message.startsWith('[vite] connecting');
}

async function withHangReport<T>(watch: RunWatch, label: string, work: Promise<T>): Promise<T> {
  const { page, name, deadlineAt, problems } = watch;
  let timer: ReturnType<typeof setTimeout> | undefined;
  const hung = new Promise<'hung'>((resolve) => {
    timer = setTimeout(() => resolve('hung'), Math.max(0, deadlineAt - Date.now()));
  });
  const replaced = watch.codeReplaced.then((what) => ({ replaced: what }));
  try {
    const outcome = await Promise.race([work.then((value) => ({ value })), hung, replaced]);
    if (outcome !== 'hung' && 'value' in outcome) return outcome.value;
    if (outcome !== 'hung') {
      throw new Error(
        `PX5 step "${label}": the editor's code was replaced mid-run (${outcome.replaced}); ` +
          'nothing measured after it is this run. Measure through ' +
          'tests/e2e/scripts/px5-local-run.py, which serves a frozen tree.',
      );
    }
  } finally {
    clearTimeout(timer);
  }
  const silence = new Promise<string>((resolve) =>
    setTimeout(
      () => resolve('the page did not answer: its main thread is blocked'),
      HANG_REPORT_TIMEOUT_MS,
    ),
  );
  const report = await Promise.race([
    page
      .evaluate(
        () =>
          (
            window as unknown as { __fpPreviewEngine?: EngineHook }
          ).__fpPreviewEngine?.debugInFlight?.() ?? null,
      )
      .catch((error: unknown) => `hang report failed: ${String(error).slice(0, 200)}`),
    silence,
  ]);
  const body = JSON.stringify({ step: label, report, console: problems.slice(-20) }, null, 1);
  mkdirSync(RESULTS_DIR, { recursive: true });
  writeFileSync(join(RESULTS_DIR, `${name}.hang.json`), `${body}\n`);
  await test.info().attach('px5-hang', { body, contentType: 'application/json' });
  throw new Error(`PX5 step "${label}" did not finish; in flight: ${body.slice(0, 2000)}`);
}

/** A WebGL error as Chrome reports it (`WebGL: INVALID_OPERATION: …`, `GL_INVALID_…`). */
const GL_ERROR = /WebGL: [A-Z_]+:|GL_INVALID_|GL_OUT_OF_MEMORY/;

test.describe('PX5 Scale row', () => {
  test.skip(!RUN, 'performance evidence runs only with FRAMEPILOT_RUN_PERF=1');
  test.describe.configure({ mode: 'serial' });

  for (const run of RUNS) {
    test(`${run.variant}/${run.mode}`, async ({ page }, testInfo) => {
      test.setTimeout((PLAY_SECONDS + 240) * 1000);
      expect(
        existsSync(join(FIXTURE, 'manifest.json')),
        'no Scale fixture: run `pnpm px5:fixture` first',
      ).toBe(true);
      const problems: string[] = [];
      // PX5.3: every GL error, not just the first 20 problems. A pass that sets uniforms on the
      // wrong program or draws into the wrong attachment type still "presents" a frame, so
      // only the driver's own complaint shows it (a key stack drew that way from MK6.1 on).
      const glErrors: string[] = [];
      page.on('console', (message) => {
        if (message.type() === 'error' || message.type() === 'warning') {
          problems.push(`${message.type()}: ${message.text().slice(0, 300)}`);
          if (GL_ERROR.test(message.text())) glErrors.push(message.text().slice(0, 300));
        }
      });
      page.on('pageerror', (error) => problems.push(`pageerror: ${error.message.slice(0, 300)}`));
      // PX5.7: once the editor is open, any navigation or hot update replaces its code.
      const replacements: string[] = [];
      let noteReplacement: (what: string) => void = () => undefined;
      const codeReplaced = new Promise<string>((resolve) => {
        noteReplacement = (what) => {
          replacements.push(what);
          resolve(what);
        };
      });
      let editorOpen = false;
      page.on('console', (message) => {
        if (editorOpen && codeReplacement(message.text())) noteReplacement(message.text());
      });
      page.on('framenavigated', (frame) => {
        if (editorOpen && frame === page.mainFrame()) noteReplacement('the page reloaded');
      });
      const watch: RunWatch = {
        page,
        name: `${run.variant}.${run.mode}`,
        deadlineAt: Date.now() + testInfo.timeout - HANG_REPORT_RESERVE_MS,
        problems,
        codeReplaced,
      };
      const guard = <T>(label: string, work: Promise<T>): Promise<T> =>
        withHangReport(watch, label, work);
      const project = await guard('open', openScale(page, run.variant, run.mode));
      editorOpen = true;

      // --- seek-to-present: deterministic targets spread over the whole timeline ------------
      const duration = await guard(
        'duration',
        page.evaluate(
          () =>
            (window as unknown as { __fpPreviewEngine: EngineHook }).__fpPreviewEngine.debugStats()
              .durationSec ?? 0,
        ),
      );
      await guard(
        'seeks',
        page.evaluate(
          async ({ seeks, durationSec, fps }) => {
            const engine = (window as unknown as { __fpPreviewEngine: EngineHook })
              .__fpPreviewEngine;
            engine.telemetry.reset();
            // An LCG, so every run seeks the same frames; none lands on a GOP boundary by design.
            let state = 12345;
            for (let i = 0; i < seeks; i++) {
              state = (state * 1103515245 + 12345) % 2147483648;
              const frame = Math.floor((state / 2147483648) * (durationSec - 1) * fps);
              await engine.seek((frame + 0.5) / fps);
            }
          },
          { seeks: SEEKS, durationSec: duration, fps: project.fps },
        ),
      );
      const seeking = await guard('telemetry after seeks', snapshot(page));

      // --- frame stepping: consecutive frames, so decode is contiguous and what is left is the
      // steady cost of ONE full-resolution composite of this timeline --------------------------
      await guard(
        'frame steps',
        page.evaluate(
          async ({ fps }) => {
            const engine = (window as unknown as { __fpPreviewEngine: EngineHook })
              .__fpPreviewEngine;
            await engine.seek(60);
            engine.telemetry.reset();
            for (let i = 1; i <= 12; i++) await engine.seek(60 + (i + 0.5) / fps);
          },
          { fps: project.fps },
        ),
      );
      const stepping = await guard('telemetry after steps', snapshot(page));
      // What the row looks like, so a number is never reported for a monitor that drew nothing.
      mkdirSync(RESULTS_DIR, { recursive: true });
      await page
        .locator('.webcodecs-preview-canvas')
        .screenshot({ path: join(RESULTS_DIR, `${run.variant}.${run.mode}.png`) });

      // --- playback through the real transport ----------------------------------------------
      await guard(
        'seek before playback',
        page.evaluate(
          async ({ gpuSync }) => {
            const engine = (window as unknown as { __fpPreviewEngine: EngineHook })
              .__fpPreviewEngine;
            await engine.seek(1);
            engine.telemetry.reset();
            engine.telemetry.gpuSync = gpuSync;
          },
          { gpuSync: run.gpuSync === true },
        ),
      );
      await page.getByRole('button', { name: 'play', exact: true }).click();
      await page.waitForTimeout((PLAY_SECONDS * 1000) / 2);
      const midway = await guard('telemetry midway', snapshot(page));
      await page.waitForTimeout((PLAY_SECONDS * 1000) / 2);
      const layersWhilePlaying = await page.evaluate(
        () =>
          (
            window as unknown as { __fpPreviewEngine: EngineHook }
          ).__fpPreviewEngine.debugPresentedFrame().layers.length,
      );
      // Recorded, not assumed: a transport that stopped by itself under load is a finding.
      const pause = page.getByRole('button', { name: 'pause', exact: true });
      const stillPlaying = await pause.isVisible();
      if (stillPlaying) await pause.click();
      const played = await guard('telemetry after playback', snapshot(page));
      // PX5.3: which path the last presented matte came from, so a run says what it measured.
      const presentedMattes = await page.evaluate(
        () =>
          (
            window as unknown as { __fpPreviewEngine: EngineHook }
          ).__fpPreviewEngine.debugPresentedMattes?.() ?? [],
      );

      const result = {
        variant: run.variant,
        mode: run.mode,
        playSeconds: PLAY_SECONDS,
        gl: await page.evaluate(() => {
          const gl = document.createElement('canvas').getContext('webgl2');
          const info = gl?.getExtension('WEBGL_debug_renderer_info');
          return gl && info ? String(gl.getParameter(info.UNMASKED_RENDERER_WEBGL)) : 'unknown';
        }),
        seekToPresent: seeking.channels.seekToPresent,
        seekExactComposite: seeking.channels.exactComposite,
        stepToPresent: stepping.channels.seekToPresent,
        stepExactComposite: stepping.channels.exactComposite,
        stepMaskRaster: stepping.channels.maskRaster,
        playback: played.playback,
        frameInterval: played.channels.frameInterval,
        composite: played.channels.composite,
        maskRaster: played.channels.maskRaster,
        keyStack: played.channels.keyStack,
        matteStack: played.channels.matteStack,
        decode: played.channels.decode,
        matteDecode: played.channels.matteDecode,
        gauges: played.gauges,
        glPoolBytesMidway: midway.gauges.glPoolBytes.current,
        renderScaleChangesMidway: midway.playback.renderScaleChanges,
        layersWhilePlaying,
        mattes: presentedMattes.map(({ tier, fromTier, state }) => ({ tier, fromTier, state })),
        gpuSync: played.gpuSync,
        stillPlayingAtEnd: stillPlaying,
        // PX5.7: what the monitor still waits on at the end (a playback that never started
        // shows its `play.audio` stage here).
        inFlightAtEnd: await guard(
          'in flight at end',
          page.evaluate(
            () =>
              (
                window as unknown as { __fpPreviewEngine: EngineHook }
              ).__fpPreviewEngine.debugInFlight?.() ?? null,
          ),
        ),
        problems: problems.slice(0, 20),
      };
      mkdirSync(RESULTS_DIR, { recursive: true });
      writeFileSync(
        join(RESULTS_DIR, `${run.variant}.${run.mode}.json`),
        `${JSON.stringify(result, null, 1)}\n`,
      );
      console.log(`[PX5] ${JSON.stringify(result)}`);
      await testInfo.attach('px5-result', {
        body: JSON.stringify(result, null, 1),
        contentType: 'application/json',
      });

      // --- invariants: the algorithm's, so the same on any machine ---------------------------
      expect(replacements, 'the editor kept the code it was opened with').toEqual([]);
      expect(glErrors, 'the compositor raised no GL error').toEqual([]);
      expect(result.seekToPresent.count, 'every seek reached the monitor').toBe(SEEKS);
      expect(result.playback.expectedFrames, 'playback ran').toBeGreaterThan(
        PLAY_SECONDS * project.fps * 0.5,
      );
      expect(result.gauges.liveDecoders.peak, 'live decoders within the pool').toBeLessThanOrEqual(
        DECODER_POOL_CAPACITY,
      );
      expect(layersWhilePlaying, 'load shedding never removes a layer').toBe(4);
      if (played.playback.renderScaleChanges === midway.playback.renderScaleChanges) {
        expect(
          result.gauges.glPoolBytes.current,
          'the GL pools stop growing on a steady timeline',
        ).toBe(result.glPoolBytesMidway);
      }
      expect(
        result.gauges.pictureCacheBytes.peak,
        'the picture cache is bounded by its budget plus what decode-ahead pins',
      ).toBeLessThanOrEqual(CACHE_BUDGET_BYTES + pinnedBytes(project, run.mode));

      if (ASSERT_BUDGETS) {
        expect(result.playback.droppedShare, 'dropped frames').toBeLessThanOrEqual(
          MAX_DROPPED_SHARE,
        );
        expect(result.seekToPresent.p95, 'seek-to-present p95 (ms)').toBeLessThanOrEqual(
          MAX_SEEK_TO_PRESENT_P95_MS,
        );
      }
    });
  }
});

/** Bytes one decode-ahead window may pin: I420 pictures per layer, and 4K matte + foreground. */
function pinnedBytes(project: ScaleProject, mode: MediaMode): number {
  const [width, height] = mode === 'proxy' ? [960, 540] : [3840, 2160];
  const picture = width * height * 1.5;
  const mattes = project.timeline.tracks
    .flatMap((track) => track.clips)
    .flatMap((clip) => clip.masks ?? [])
    .filter((mask) => mask.kind === 'matte').length;
  const matte = 3840 * 2160 * (1 + 4);
  return PINNED_FRAMES * (project.assets.length * picture + mattes * matte);
}
