/**
 * Build-time Dodo Payments price fetcher (runs in `prebuild`).
 *
 * WHY: the pricing page must reflect the REAL product prices, not hand-typed
 * numbers. When the Dodo API env is present we read the live product prices and
 * write `src/lib/pricing.generated.ts`; the pricing UI merges it over the typed
 * fallback. This step is intentionally NON-FATAL — any failure (no env, network,
 * auth) leaves the committed `null` in place so the build stays green and the
 * fallback launch pricing is shown.
 *
 * Env (server/build-only — never bundled):
 *   DODO_PAYMENTS_API_KEY           merchant API key (bearer)
 *   DODO_PAYMENTS_ENVIRONMENT       'live' (default) | 'test'
 *   NEXT_PUBLIC_DODO_PRODUCT_ID_MONTHLY / _ANNUAL  the two subscription products
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { BillingCycle, PlanPrice } from '../src/lib/pricing-types';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/lib/pricing.generated.ts');

const API_HOST: Record<'live' | 'test', string> = {
  live: 'https://live.dodopayments.com',
  test: 'https://test.dodopayments.com',
};

/**
 * Internal plan id → the env var holding its Dodo product id per cadence. A Dodo
 * product carries exactly one recurring price, so each cadence is a separate
 * product: "FramePilot Monthly" and "FramePilot Yearly".
 */
const PRODUCT_ENV_BY_PLAN: Record<string, Record<BillingCycle, string>> = {
  pro: {
    monthly: 'NEXT_PUBLIC_DODO_PRODUCT_ID_MONTHLY',
    annual: 'NEXT_PUBLIC_DODO_PRODUCT_ID_ANNUAL',
  },
};

/** A Dodo price is in the smallest currency unit; the UI shows whole dollars. */
interface DodoProduct {
  price?: { price?: number | null; currency?: string | null } | null;
  is_recurring?: boolean;
}

async function fetchProductAmount(
  productId: string,
  host: string,
  apiKey: string,
): Promise<{ amount: number; currency: string } | null> {
  const res = await fetch(`${host}/products/${encodeURIComponent(productId)}`, {
    headers: { Authorization: `Bearer ${apiKey}` },
  });
  if (!res.ok) {
    console.warn(`[fetch-pricing] product ${productId} request failed (${res.status}).`);
    return null;
  }
  const product = (await res.json()) as DodoProduct;
  const cents = product.price?.price;
  if (typeof cents !== 'number') return null;
  return { amount: cents / 100, currency: product.price?.currency ?? 'USD' };
}

async function fetchPricing(): Promise<string> {
  const apiKey = process.env.DODO_PAYMENTS_API_KEY;
  const host = API_HOST[process.env.DODO_PAYMENTS_ENVIRONMENT === 'test' ? 'test' : 'live'];
  if (!apiKey) return nullFile('DODO_PAYMENTS_API_KEY not set — using fallback pricing.');

  try {
    const out: Record<
      string,
      { price: PlanPrice | null; dodoProductIds?: Partial<Record<BillingCycle, string>> }
    > = {};
    let currency = 'USD';

    for (const [planId, envByCycle] of Object.entries(PRODUCT_ENV_BY_PLAN)) {
      const monthlyId = process.env[envByCycle.monthly];
      const annualId = process.env[envByCycle.annual];
      if (!monthlyId && !annualId) continue;

      const [monthly, annual] = await Promise.all([
        monthlyId ? fetchProductAmount(monthlyId, host, apiKey) : null,
        annualId ? fetchProductAmount(annualId, host, apiKey) : null,
      ]);
      currency = monthly?.currency ?? annual?.currency ?? currency;

      // If only one cadence exists, derive the other so the toggle never shows a
      // gap (monthly ≈ annual/12; annual ≈ monthly×12).
      const monthlyAmount = monthly?.amount ?? (annual ? annual.amount / 12 : null);
      const annualAmount = annual?.amount ?? (monthly ? monthly.amount * 12 : null);

      out[planId] = {
        price:
          monthlyAmount != null && annualAmount != null
            ? { monthly: Math.round(monthlyAmount), annual: Math.round(annualAmount) }
            : null,
        dodoProductIds: {
          ...(monthlyId ? { monthly: monthlyId } : {}),
          ...(annualId ? { annual: annualId } : {}),
        },
      };
    }

    if (Object.keys(out).length === 0) return nullFile('No Dodo product ids configured.');

    return generatedFile({ fetchedAt: new Date().toISOString(), currency, plans: out });
  } catch (err) {
    return nullFile(`Dodo fetch error: ${(err as Error).message}`);
  }
}

function nullFile(reason: string): string {
  console.warn(`[fetch-pricing] ${reason}`);
  return (
    HEADER +
    "import type { GeneratedPricing } from './pricing-types';\n\n" +
    'export const GENERATED_PRICING: GeneratedPricing | null = null;\n'
  );
}

function generatedFile(data: unknown): string {
  console.log('[fetch-pricing] Wrote live Dodo Payments pricing.');
  return (
    HEADER +
    "import type { GeneratedPricing } from './pricing-types';\n\n" +
    `export const GENERATED_PRICING: GeneratedPricing = ${JSON.stringify(data, null, 2)};\n`
  );
}

const HEADER =
  '/* AUTO-GENERATED by scripts/fetch-pricing.ts. Do not edit by hand. */\n' +
  '/* eslint-disable */\n';

const contents = await fetchPricing();
await writeFile(OUT, contents, 'utf8');
