"""Project Brain — the derived, per-project SQLite substrate (plan B0).

WHY: analysis results (silence, scenes, loudness, transcripts, vision labels)
were ephemeral — recomputed every session and discarded. The brain persists
everything the substrate learns about a project's media so it is queryable,
cacheable, and provenance-tracked, mirroring the architecture proven by
davinci-resolve-mcp's ``timeline_brain.sqlite``.

Non-negotiable invariants (ORCHESTRATION_ENHANCEMENT_PLAN.md §2):

1. ``project.fp.json`` stays the single canonical document. The brain is a
   *derived, rebuildable cache* — deleting it loses time, never truth.
2. Single writer: only this Python sidecar writes ``brain.sqlite``.
3. Every path stays inside the sandbox (:func:`~framepilot_engine.safety.resolve_within`).
4. Provenance: every field write carries ``source: machine|model|human`` and
   human values are never silently overwritten (see :mod:`.store`).
"""

from framepilot_engine.brain.captioner import (
    CAPTION_INSTRUCTION,
    NO_VISION_PROVIDER_REASON,
    CaptionerResolution,
    CaptionError,
    CaptionProviderConfig,
    CaptionProviderKind,
    SceneCaptioner,
    resolve_captioner,
)
from framepilot_engine.brain.embeddings import (
    Embedder,
    EmbedderResolution,
    cosine_top_k,
    pack_vector,
    resolve_embedder,
    unpack_vector,
)
from framepilot_engine.brain.fts import (
    DIALOGUE_GAP_SECONDS,
    fts_match_expression,
    segment_utterances,
)
from framepilot_engine.brain.keyring import (
    EXHAUSTED_REASON,
    FATAL_STATUSES,
    KeyHealth,
    KeyRing,
    KeyRingExhaustedError,
    KeyState,
    mask_key,
    parse_keys,
)
from framepilot_engine.brain.memory import (
    MAX_TIER_BYTES,
    append_memory_entry,
    asset_section,
    bin_summary_path,
    fit_entries,
    latest_session_note,
    memory_dir,
    parse_entries,
    read_tier,
    render_bin_summary,
    render_entry,
    render_tier_file,
    tail_entries,
    tier_path,
    write_bin_summary,
)
from framepilot_engine.brain.models import (
    AnalysisResultRow,
    AssetRow,
    BrainStatus,
    EmbeddingRow,
    FieldChangeRow,
    FieldConflict,
    FieldRow,
    FrameRow,
    JobRow,
    JobState,
    MemoryEntry,
    MemoryTier,
    Provenance,
    SearchHit,
    SearchHitType,
    SessionContext,
    TranscriptUtterance,
    VisualCaptionRow,
    VisualSpanRow,
    VisualVectorRow,
    WriteFieldResult,
)
from framepilot_engine.brain.similar import (
    AssetDigest,
    blend_hits,
    build_embedding_rows,
    semantic_hits,
)
from framepilot_engine.brain.soul import (
    PROMOTION_MIN_PROJECTS,
    SoulDoc,
    append_soul_note,
    note_correction,
    read_soul_doc,
    record_sighting,
    soul_digest,
    soul_root,
)
from framepilot_engine.brain.store import (
    BrainError,
    BrainSchemaError,
    BrainStore,
    brain_dir_for,
    brain_status,
    open_brain,
)
from framepilot_engine.brain.vector_store import (
    BACKEND_BRUTE_FORCE,
    BACKEND_SQLITE_VEC,
    VisualHit,
    VisualVectorStore,
    vec_available,
)
from framepilot_engine.brain.visual_embed import (
    EMBEDDINGS_URL,
    MODEL_ID,
    NO_API_KEY_REASON,
    EmbedResult,
    VisualEmbedClient,
    VisualEmbedderResolution,
    VisualEmbedError,
    resolve_visual_embedder,
)
from framepilot_engine.brain.visual_search import (
    RRF_K,
    EvidencePacket,
    RankedList,
    build_evidence_packets,
    project_span_to_timeline,
    reciprocal_rank_fusion,
    transcript_overlap,
)

__all__ = [
    "BACKEND_BRUTE_FORCE",
    "BACKEND_SQLITE_VEC",
    "CAPTION_INSTRUCTION",
    "DIALOGUE_GAP_SECONDS",
    "EMBEDDINGS_URL",
    "EXHAUSTED_REASON",
    "FATAL_STATUSES",
    "MAX_TIER_BYTES",
    "MODEL_ID",
    "NO_API_KEY_REASON",
    "NO_VISION_PROVIDER_REASON",
    "PROMOTION_MIN_PROJECTS",
    "RRF_K",
    "AnalysisResultRow",
    "AssetDigest",
    "AssetRow",
    "BrainError",
    "BrainSchemaError",
    "BrainStatus",
    "BrainStore",
    "CaptionError",
    "CaptionProviderConfig",
    "CaptionProviderKind",
    "CaptionerResolution",
    "EmbedResult",
    "Embedder",
    "EmbedderResolution",
    "EmbeddingRow",
    "EvidencePacket",
    "FieldChangeRow",
    "FieldConflict",
    "FieldRow",
    "FrameRow",
    "JobRow",
    "JobState",
    "KeyHealth",
    "KeyRing",
    "KeyRingExhaustedError",
    "KeyState",
    "MemoryEntry",
    "MemoryTier",
    "Provenance",
    "RankedList",
    "SceneCaptioner",
    "SearchHit",
    "SearchHitType",
    "SessionContext",
    "SoulDoc",
    "TranscriptUtterance",
    "VisualCaptionRow",
    "VisualEmbedClient",
    "VisualEmbedError",
    "VisualEmbedderResolution",
    "VisualHit",
    "VisualSpanRow",
    "VisualVectorRow",
    "VisualVectorStore",
    "WriteFieldResult",
    "append_memory_entry",
    "append_soul_note",
    "asset_section",
    "bin_summary_path",
    "blend_hits",
    "brain_dir_for",
    "brain_status",
    "build_embedding_rows",
    "build_evidence_packets",
    "cosine_top_k",
    "fit_entries",
    "fts_match_expression",
    "latest_session_note",
    "mask_key",
    "memory_dir",
    "note_correction",
    "open_brain",
    "pack_vector",
    "parse_entries",
    "parse_keys",
    "project_span_to_timeline",
    "read_soul_doc",
    "read_tier",
    "reciprocal_rank_fusion",
    "record_sighting",
    "render_bin_summary",
    "render_entry",
    "render_tier_file",
    "resolve_captioner",
    "resolve_embedder",
    "resolve_visual_embedder",
    "segment_utterances",
    "semantic_hits",
    "soul_digest",
    "soul_root",
    "tail_entries",
    "tier_path",
    "transcript_overlap",
    "unpack_vector",
    "vec_available",
    "write_bin_summary",
]
