import { readFile, mkdtemp, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import type { CapabilityPackCatalog, CapabilityPackReleaseCore } from '../contracts.js';
import { releaseDigest, verifySignedCatalog } from './catalog-verifier.js';
import { runReleaseCli } from './release-cli.js';
import { signCatalog } from './release-tooling.js';

function io() {
  const out: string[] = [];
  const err: string[] = [];
  return {
    out,
    err,
    handlers: { stdout: (m: string) => out.push(m), stderr: (m: string) => err.push(m) },
  };
}

async function workspace(): Promise<string> {
  return mkdtemp(path.join(os.tmpdir(), 'framepilot-rootkey-'));
}

function releaseCore(): CapabilityPackReleaseCore {
  return {
    id: 'framepilot.subject-intelligence',
    version: '1.0.0',
    displayName: 'Subject Intelligence',
    description: 'Detection and segmentation.',
    channel: 'stable',
    capabilities: ['subject.detect', 'subject.segment'],
    licenses: [
      {
        spdx: 'Apache-2.0',
        name: 'Apache License 2.0',
        noticeUrl: 'https://framepilot.ai/licenses/apache-2.0',
        redistribution: 'allowed',
      },
    ],
    privacy: { execution: 'local', mediaLeavesDevice: false, disclosure: 'Runs locally.' },
    compatibility: { minAppVersion: '1.0.0', workerProtocolVersion: 1 },
    artifacts: [
      {
        os: 'darwin',
        arch: 'arm64',
        url: 'https://packs.framepilot.ai/artifacts/a/worker.zip',
        sha256: 'a'.repeat(64),
        sizeBytes: 10,
        unpackedSizeBytes: 20,
        format: 'zip',
        entrypoint: 'bin/worker',
        maxFileCount: 2,
        files: ['NOTICE.txt', 'bin/worker'],
        executableTrust: { kind: 'macos_codesign', teamIdentifier: 'ABCDE12345' },
      },
    ],
    dependencies: [],
    conflicts: [],
  };
}

function catalog(): CapabilityPackCatalog {
  const core = releaseCore();
  return {
    schemaVersion: 1,
    generatedAt: '2026-08-14T00:00:00.000Z',
    expiresAt: '2026-09-14T00:00:00.000Z',
    releases: [{ ...core, releaseDigest: releaseDigest(core) }],
    delegatedKeys: [],
  };
}

describe('generate-root-key', () => {
  it('produces a key that actually signs a catalog the app will trust', async () => {
    // The end-to-end property that matters: a root generated by this command,
    // used to sign a catalog, must verify against the app's own verifier. Anything
    // less proves only that two files were written.
    const root = await workspace();
    const privateKeyPath = path.join(root, 'root.pem');
    const trustedKeysPath = path.join(root, 'capability-pack-root-keys.json');
    const console_ = io();

    const code = await runReleaseCli(
      ['generate-root-key', 'framepilot.root.2026', privateKeyPath, trustedKeysPath],
      console_.handlers,
    );

    expect(code, console_.err.join('\n')).toBe(0);
    const trusted = JSON.parse(await readFile(trustedKeysPath, 'utf8')) as {
      keyId: string;
      publicKeyPem: string;
    }[];
    const signed = signCatalog(catalog(), {
      keyId: 'framepilot.root.2026',
      privateKeyPem: await readFile(privateKeyPath, 'utf8'),
    });

    expect(() => verifySignedCatalog(signed, trusted)).not.toThrow();
  });

  it('writes the trusted-key file in the shape the desktop loader requires', async () => {
    const root = await workspace();
    const console_ = io();

    await runReleaseCli(
      [
        'generate-root-key',
        'framepilot.root.2026',
        path.join(root, 'root.pem'),
        path.join(root, 'keys.json'),
      ],
      console_.handlers,
    );

    const trusted = JSON.parse(await readFile(path.join(root, 'keys.json'), 'utf8')) as unknown;
    // A top-level array of {keyId, publicKeyPem} — see loadCapabilityPackRootKeys.
    expect(Array.isArray(trusted)).toBe(true);
    expect(trusted).toHaveLength(1);
    expect(trusted[0]).toMatchObject({ keyId: 'framepilot.root.2026' });
    expect((trusted as { publicKeyPem: string }[])[0]!.publicKeyPem).toContain('BEGIN PUBLIC KEY');
  });

  it('never prints the private key', async () => {
    // A root that has been through a terminal scrollback or a CI log is burned.
    const root = await workspace();
    const console_ = io();

    await runReleaseCli(
      [
        'generate-root-key',
        'framepilot.root.2026',
        path.join(root, 'root.pem'),
        path.join(root, 'keys.json'),
      ],
      console_.handlers,
    );

    const everythingPrinted = [...console_.out, ...console_.err].join('\n');
    expect(everythingPrinted).not.toContain('PRIVATE KEY');
    expect(everythingPrinted).toContain('offline');
  });

  it('writes the private key readable only by its owner', async () => {
    const root = await workspace();
    const privateKeyPath = path.join(root, 'root.pem');

    await runReleaseCli(
      ['generate-root-key', 'framepilot.root.2026', privateKeyPath, path.join(root, 'keys.json')],
      io().handlers,
    );

    const mode = (await stat(privateKeyPath)).mode & 0o777;
    expect(mode & 0o077).toBe(0);
  });

  it('refuses to overwrite an existing private key', async () => {
    // Silently replacing a root would invalidate every catalog already signed
    // with it and every installed pack's trust chain.
    const root = await workspace();
    const privateKeyPath = path.join(root, 'root.pem');
    const args = [
      'generate-root-key',
      'framepilot.root.2026',
      privateKeyPath,
      path.join(root, 'keys.json'),
    ];
    await runReleaseCli(args, io().handlers);

    const second = io();
    const code = await runReleaseCli(args, second.handlers);

    expect(code).toBe(1);
    expect(second.err.join('\n')).toMatch(/exist/i);
  });

  it('rejects a key id the trust store could never load', async () => {
    const root = await workspace();
    const console_ = io();

    const code = await runReleaseCli(
      [
        'generate-root-key',
        'Not A Valid Id',
        path.join(root, 'root.pem'),
        path.join(root, 'keys.json'),
      ],
      console_.handlers,
    );

    expect(code).toBe(1);
    expect(console_.err.join('\n')).toMatch(/not a valid identifier/i);
  });

  it('a catalog signed by a different root is refused', async () => {
    // The negative control: trust must come from the key, not from the file being
    // present and well formed.
    const root = await workspace();
    await runReleaseCli(
      [
        'generate-root-key',
        'framepilot.root.2026',
        path.join(root, 'a.pem'),
        path.join(root, 'a.json'),
      ],
      io().handlers,
    );
    await runReleaseCli(
      [
        'generate-root-key',
        'framepilot.root.2026',
        path.join(root, 'b.pem'),
        path.join(root, 'b.json'),
      ],
      io().handlers,
    );

    const signedByB = signCatalog(catalog(), {
      keyId: 'framepilot.root.2026',
      privateKeyPem: await readFile(path.join(root, 'b.pem'), 'utf8'),
    });
    const trustedA = JSON.parse(await readFile(path.join(root, 'a.json'), 'utf8')) as {
      keyId: string;
      publicKeyPem: string;
    }[];

    expect(() => verifySignedCatalog(signedByB, trustedA)).toThrow();
  });
});
